### ISSUE TITLE
RE: ModuleNotFoundError: No module named 'clitable'

### ISSUE THREAD

**Issue by Birajan2019** [Juniper/py-junos-eznc#1022]
Hi Guys,

I used "pip install junos-eznc" to automatically download and install all of the required packages for pyez.
The download and install process seemed to go fine, but when I try to execute the command "from jnpr.junos import Device"
I get the following errors. Can somebody please help?

C:\Users\firstname.lastname>python
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

>>> from jnpr.junos import Device
Traceback (most recent call last):
  File "C:\Users\firstname.lastname\AppData\Local\Programs\Python\Python38\lib\site-packages\ntc_templates\parse.py", line 5, in <module>
    from textfsm import clitable
  File "C:\Users\firstname.lastname\AppData\Local\Programs\Python\Python38\lib\site-packages\textfsm\clitable.py", line 41, in <module>
    from textfsm import texttable
  File "C:\Users\firstname.lastname\AppData\Local\Programs\Python\Python38\lib\site-packages\textfsm\texttable.py", line 42, in <module>
    from textfsm import terminal
  File "C:\Users\firstname.lastname\AppData\Local\Programs\Python\Python38\lib\site-packages\textfsm\terminal.py", line 25, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\firstname.lastname\AppData\Local\Programs\Python\Python38\lib\site-packages\jnpr\junos\__init__.py", line 3, in <module>
    from jnpr.junos.factory.to_json import PyEzJSONEncoder
  File "C:\Users\firstname.lastname\AppData\Local\Programs\Python\Python38\lib\site-packages\jnpr\junos\factory\__init__.py", line 4, in <module>
    from jnpr.junos.factory.factory_loader import FactoryLoader
  File "C:\Users\firstname.lastname\AppData\Local\Programs\Python\Python38\lib\site-packages\jnpr\junos\factory\factory_loader.py", line 14, in <module>
    from jnpr.junos.factory.factory_cls import *
  File "C:\Users\firstname.lastname\AppData\Local\Programs\Python\Python38\lib\site-packages\jnpr\junos\factory\factory_cls.py", line 7, in <module>
    from jnpr.junos.factory.cmdtable import CMDTable
  File "C:\Users\firstname.lastname\AppData\Local\Programs\Python\Python38\lib\site-packages\jnpr\junos\factory\cmdtable.py", line 18, in <module>
    from ntc_templates import parse as ntc_parse
  File "C:\Users\firstname.lastname\AppData\Local\Programs\Python\Python38\lib\site-packages\ntc_templates\parse.py", line 7, in <module>
    import clitable
ModuleNotFoundError: No module named 'clitable'
>>>

If it helps, here is the output of the following commnands:

**python -V
pip -V
pip list**

C:\Users\first.lastnae>python -V
Python 3.8.2

C:\Users\first.lastnae>pip -V
pip 20.0.2 from c:\users\first.lastnae\appdata\local\programs\python\python38\lib\site-packages\pip (python 3.8)

C:\Users\first.lastnae>pip list
Package               Version
--------------------- -------
bcrypt                3.1.7
cffi                  1.14.0
colorama              0.4.3
cryptography          2.9
future                0.18.2
Jinja2                2.11.2
junos-eznc            2.4.0
lxml                  4.5.0
MarkupSafe            1.1.1
ncclient              0.6.7
netaddr               0.7.19
netmiko               3.1.0
ntc-templates         1.4.0
paramiko              2.7.1
pip                   20.0.2
pycparser             2.20
PyNaCl                1.3.0
pyparsing             2.4.7
pyserial              3.4
PyYAML                5.3.1
scp                   0.13.2
setuptools            41.2.0
six                   1.14.0
terminal              0.4.0
textfsm               1.1.0
transitions           0.8.1
yamlordereddictloader 0.4.0

**Comment by ntwrkguru** [comment]
Please see #1015. Fixed by #1019 and is available in master.

```bash
# pip install -U git+https://github.com/Juniper/py-junos-eznc.git
```

**Comment by Birajan2019** [comment]
Thanks @ntwrkguru. I just pip uninstalled textfsm 1.1.0 and reinstalled textfsm 0.4.1 for the fix.

**Comment by ntwrkguru** [comment]
@Birajan2019 Good. Ok to close then?

**Comment by Birajan2019** [comment]
Yes, @ntwrkguru, good to close.
