### ISSUE TITLE
JSON "Invalid control character" on extensive=True get-route-information

### ISSUE THREAD

**Issue by andydavidson** [Juniper/py-junos-eznc#1029]
Can't do extensive=True on rpc.get-route-information without tickling a JSON parsing error

The issue appears to be that there is a newline character inside the JSON.

The JSON loads when I append strict=False to the file /usr/local/lib/python3.5/dist-packages/jnpr/junos/device.py

```
user@ubuntu:~/ribtest$ python3 bin/scratch.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/jnpr/junos/device.py", line 838, in execute
    return json.loads(rpc_rsp_e.text)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 376 column 39 (char 11673)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/scratch.py", line 10, in <module>
    rt.load_table()
  File "./lib/testdevice.py", line 38, in load_table
    extensive=True
  File "/usr/local/lib/python3.5/dist-packages/jnpr/junos/rpcmeta.py", line 348, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/usr/local/lib/python3.5/dist-packages/jnpr/junos/decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/jnpr/junos/decorators.py", line 31, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/jnpr/junos/device.py", line 845, in execute
    raise JSONLoadError(ex, rpc_rsp_e.text)
jnpr.junos.exception.JSONLoadError: JSONLoadError(reason: Invalid control character at: line 376 column 39 (char 11673), 
The offending config appears to be: 
374:                         "output" : [
375:                         {
376:                             "data" : "				10.101.0.5/32 Originating RIB: inet.3\n				  Metric: 1	Node path count: 1\n				  Forwarding nexthops: 1\n					Nexthop: 10.100.1.9 via ge-0/0/2.0\n					Session Id: 141"
377:                         }
378:                         ]
)
```

**Comment by vnitinv** [comment]
@andydavidson Which version of junos you are running? can you share the O/P for show route extensive  | display json. You can unincast me at nitinkr [at] juniper [dot] net

**Comment by andydavidson** [comment]
@vnitinv Nitin, thanks for your reply!  This is what we have for JUNOS in our lab where I am running this:

Model: vmx
Junos: 18.2R1.9

I will send you my show route extensive by email now.

**Comment by andydavidson** [comment]
Is there any more on this?  I think if the newline character was stripped from the extensive output, the problem would go away.

**Comment by andydavidson** [comment]
I have submitted a pull request for the change which makes this problem go away on my system, hope you can incorporate it into a release soon.
