### ISSUE TITLE
Device is closing the session

### ISSUE THREAD

**Issue by jutkarsh079** [Juniper/py-junos-eznc#1039]
I am just testing to connect to device but the device is closing the connection unexpectedly.

    
    from pprint import pprint
    from jnpr.junos import Device

    with Device(host=TESTHOST, 
            user=TESTUSER, 
            password=TESTPASS) as dev:

    pprint( dev.facts )

Here is the traceback:

`Traceback (most recent call last):
  File "test_jnpr.junos.py", line 10, in <module>
    password=TESTPASS) as dev:
  File "/usr/lib/python2.7/site-packages/jnpr/junos/device.py", line 1391, in __enter__
    self.open()
  File "/usr/lib/python2.7/site-packages/jnpr/junos/device.py", line 1345, in open
    raise cnx_err
jnpr.junos.exception.ConnectError: ConnectError(host: 192.168.82.104, msg: Unexpected session close)`

**Comment by ntwrkguru** [comment]
What is the device?

**Comment by jutkarsh079** [comment]
@ntwrkguru  its a juniper mx960 router

**Comment by ntwrkguru** [comment]
It *shouldn't* matter, but can you try with Python3? Python 2 is dead. I'd like to rule out something with a Python2 library.  Also, please try this as well and post the output:
`ssh TESTUSER@192.168.82.104 -p 830 -s netconf`

**Comment by jutkarsh079** [comment]
Same thing with python3.

  ```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/jnpr/junos/device.py", line 1264, in open
    self.__class__.ON_JUNOS})
  File "/usr/local/lib/python3.7/site-packages/ncclient/manager.py", line 176, in connect
    return connect_ssh(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/ncclient/manager.py", line 141, in connect_ssh
    session.connect(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/ncclient/transport/ssh.py", line 385, in connect
    self._post_connect()
  File "/usr/local/lib/python3.7/site-packages/ncclient/transport/session.py", line 116, in _post_connect
    raise error[0]
  File "/usr/local/lib/python3.7/site-packages/ncclient/transport/ssh.py", line 498, in run
    raise SessionCloseError(self._buffer.getvalue())
ncclient.transport.errors.SessionCloseError: Unexpected session close

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_jnpr.junos.py", line 10, in <module>
    password=TESTPASS) as dev:
  File "/usr/local/lib/python3.7/site-packages/jnpr/junos/device.py", line 1346, in __enter__
    self.open()
  File "/usr/local/lib/python3.7/site-packages/jnpr/junos/device.py", line 1305, in open
    raise cnx_err
jnpr.junos.exception.ConnectError: ConnectError(host: 192.168.82.104, msg: Unexpected session
```


I am able to ssh into machine with 
```
`ssh TESTUSER@192.168.82.104 -p 830 -s netconf`

<!-- No zombies were killed during the creation of this user interface -->
<!-- user Singtel-RW, class j-Singtel-RW -->
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file</capability>
    <capability>urn:ietf:params:xml:ns:netconf:base:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:confirmed-commit:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:validate:1.0</capability>
    <capability>urn:ietf:params:xml:ns:netconf:capability:url:1.0?protocol=http,ftp,file</capability>
    <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring</capability>
    <capability>http://xml.juniper.net/netconf/junos/1.0</capability>
    <capability>http://xml.juniper.net/dmi/system/1.0</capability>
  </capabilities>
  <session-id>17389</session-id>
</hello>
```

**Comment by rahkumar651991** [comment]
@jutkarsh079  Try adding these lines in PyEZ script to get more logging. 
import logging
logging.basicConfig(level=logging.DEBUG)

Marking this issue as inactive as no discussion has happened for long time. In case there is a related query, update it.
