### ISSUE TITLE
runtime error: when trying to remove_namespaces

### ISSUE THREAD

**Issue by nskalis** [Juniper/py-junos-eznc#1044]
Hi,

I am facing a runtime error (for the first time) when trying to download the BGP routing table on a router

```
2020-06-10 16:26:07,626 | ERROR | 47832 | pulse_cdn | get_bgp_routes | querying `xxx` for internet bgp routes caused `XMLSyntaxError('Document is empty, line 1, column 1',)`
Traceback (most recent call last):
  File "/home/app/ip-spotlight/code/app/registry/pulse_cdn.py", line 77, in get_bgp_routes
    protocol="bgp", active_path=True, detail=True, dev_timeout=3 * 60 * 60
  File "/usr/local/lib/python3.6/site-packages/jnpr/junos/rpcmeta.py", line 346, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/usr/local/lib/python3.6/site-packages/jnpr/junos/decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jnpr/junos/decorators.py", line 23, in wrapper
    result = function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jnpr/junos/device.py", line 799, in execute
    'filter_xml'))
  File "/usr/local/lib/python3.6/site-packages/jnpr/junos/decorators.py", line 116, in wrapper
    rsp = function(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jnpr/junos/device.py", line 1381, in _rpc_reply
    return self._conn.rpc(rpc_cmd_e, filter_xml)._NCElement__doc
  File "/usr/local/lib/python3.6/site-packages/ncclient/manager.py", line 236, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/ncclient/operations/third_party/juniper/rpc.py", line 52, in request
    return self._request(rpc)
  File "/usr/local/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 350, in _request
    return NCElement(self._reply, self._device_handler.transform_reply(), huge_tree=self._huge_tree)
  File "/usr/local/lib/python3.6/site-packages/ncclient/xml_.py", line 174, in __init__
    self.__doc = self.remove_namespaces(self.__result)
  File "/usr/local/lib/python3.6/site-packages/ncclient/xml_.py", line 223, in remove_namespaces
    parser=self.__parser)
  File "src/lxml/etree.pyx", line 3235, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1757, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1068, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1
```

If I download the command output manually, it begins with:
```
$ more run/ext/inet.bgp.cdn.ziggo.xml 
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/16.1R7/junos">
    <route-information xmlns="http://xml.juniper.net/junos/16.1R7/junos-routing">
        <!-- keepalive -->
        <route-table>
            <table-name>inet.0</table-name>
            <destination-count>973285</destination-count>
            <total-route-count>1945087</total-route-count>
            <active-route-count>973270</active-route-count>
            <holddown-route-count>30</holddown-route-count>
            <hidden-route-count>111</hidden-route-count>
            <rt junos:style="detail">
                <rt-destination>1.0.0.0</rt-destination>
                <rt-prefix-length>24</rt-prefix-length>
...
```

I can share the whole file in a unicast way, if desired.

Would you be so kind to advise on what might be wrong and how to fix this?

**Comment by rahkumar651991** [comment]
Can you share the xml and netconf trace? 
Unicast it to jnpr-community-netdev@juniper.net

**Comment by nskalis** [comment]
thanks @rahkumar651991 for looking at it

not sure what you mean with Netconf trace, maybe this one (?)
```
2020-06-10 16:26:07,626 | ERROR | 47832 | pulse_cdn | get_bgp_routes | querying `asd-tr0042-dr101` for internet bgp routes caused `XMLSyntaxError('Document is empty, line 1, column 1',)`
Traceback (most recent call last):
  File "/home/app/ip-spotlight/code/app/registry/pulse_cdn.py", line 77, in get_bgp_routes
    protocol="bgp", active_path=True, detail=True, dev_timeout=3 * 60 * 60
  File "/usr/local/lib/python3.6/site-packages/jnpr/junos/rpcmeta.py", line 346, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/usr/local/lib/python3.6/site-packages/jnpr/junos/decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jnpr/junos/decorators.py", line 23, in wrapper
    result = function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jnpr/junos/device.py", line 799, in execute
    'filter_xml'))
  File "/usr/local/lib/python3.6/site-packages/jnpr/junos/decorators.py", line 116, in wrapper
    rsp = function(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/jnpr/junos/device.py", line 1381, in _rpc_reply
    return self._conn.rpc(rpc_cmd_e, filter_xml)._NCElement__doc
  File "/usr/local/lib/python3.6/site-packages/ncclient/manager.py", line 236, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/ncclient/operations/third_party/juniper/rpc.py", line 52, in request
    return self._request(rpc)
  File "/usr/local/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 350, in _request
    return NCElement(self._reply, self._device_handler.transform_reply(), huge_tree=self._huge_tree)
  File "/usr/local/lib/python3.6/site-packages/ncclient/xml_.py", line 174, in __init__
    self.__doc = self.remove_namespaces(self.__result)
  File "/usr/local/lib/python3.6/site-packages/ncclient/xml_.py", line 223, in remove_namespaces
    parser=self.__parser)
  File "src/lxml/etree.pyx", line 3235, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1757, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1068, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1
```

the .xml output is on its way

**Comment by ydnath** [comment]
@nskalis Please refer https://www.juniper.net/documentation/en_US/junos/topics/example/netconf-traceoptions-configuring.html

**Comment by vnitinv** [comment]
@nskalis We will also need code snippet from where this is failing, Are you using filter_xml keyword by any chance?

**Comment by nskalis** [comment]
@vnitinv yes, indeed

```
def get_bgp_routes(target, filename):
    logger.info("querying `{}` for internet bgp routes".format(target["host_name"]))
    pyez = Device(
        host=target["host_ipaddr"],
        user=os.environ["USR_NETOPS"],
        passwd=os.environ["PASS_NETOPS"],
        port=22,
        gather_facts=False,
    )
    try:
        pyez.open(normalize=True)
        docs = pyez.rpc.get_route_information(
            protocol="bgp", active_path=True, detail=True, dev_timeout=3 * 60 * 60
        )
        with open(
            "{}/ip-spotlight/run/ext/{}".format(os.environ["DIR_APP"], filename), "a+"
        ) as f:
            for route in docs.xpath(
                "//route-information/route-table[table-name='inet.0' or table-name='inet6.0']/rt"
            ):
                data = {
                    "host_name": target["host_name"],
                    "prefix": "{}/{}".format(
                        route.xpath("./rt-destination/text()")[0],
                        route.xpath("./rt-prefix-length/text()")[0],
                    ),
                    "proto_nexthop": route.xpath("./rt-entry/protocol-nh/to/text()")[0],
                    "as_path": route.xpath("./rt-entry/as-path/text()")[0],
                    "bgp_comms": route.xpath("./rt-entry/communities/community/text()"),
                }
                f.write(json.dumps(data))
                f.write(os.linesep)
    except Exception as e:
        logger.error(
            "querying `{}` for internet bgp routes caused `{}`".format(
                target["host_name"], repr(e)
            ),
            exc_info=True,
        )
    finally:
        pyez.close()
```

**Comment by vnitinv** [comment]
Thanks @nskalis The code is fine.

**Comment by nskalis** [comment]
Thank you guys for the support last Friday.

Using `junos-eznc==2.3.1` and passing `huge_tree` at the `Device` level
```
gather_facts=False,
huge_tree=True, 
```

After enabling the `DEBUG` logging level the error mentioned is:
```
</rt>
</route-table>
</route-information>
</rpc-reply>
DEBUG:ncclient.operations.rpc:[host 62.179.149.157 session-id 67814] Delivering to <ncclient.operations.third_party.juniper.rpc.ExecuteRpc object at 0x7ff623f8a9e8>
DEBUG:ncclient.transport.parser:[host 62.179.149.157 session-id 67814] parsing netconf v1.0
DEBUG:ncclient.transport.ssh:[host 62.179.149.157 session-id 67814] Broke out of main loop, error=SessionCloseError("Unexpected session close\nIN_BUFFER: `b'<!-- session end at 2020-06-21 11:47:12 CEST -->\\n'`",)
DEBUG:ncclient.transport.ssh:[host 62.179.149.157 session-id 67814] dispatching error to <jnpr.junos.device.DeviceSessionListener object at 0x7ff5d26526a0>
DEBUG:ncclient.transport.ssh:[host 62.179.149.157 session-id 67814] dispatching error to <ncclient.transport.session.NotificationHandler object at 0x7ff623f8a0b8>
DEBUG:ncclient.transport.ssh:[host 62.179.149.157 session-id 67814] dispatching error to <ncclient.operations.rpc.RPCReplyListener object at 0x7ff623f8a828>
DEBUG:ncclient.transport.ssh:EOF in transport thread
```

Could you please advise how-to progress with it ?

**Comment by nskalis** [comment]
```
pyez.open(normalize=True)
pyez.transform = lambda: remove_namespaces
docs = pyez.rpc.get_route_information(...)
```

`remove_namespaces` did the trick, thank you!
