### ISSUE TITLE
Junos Evolution - Routing engine info is not populated in device facts

### ISSUE THREAD

**Issue by rahuluk86** [Juniper/py-junos-eznc#1125]
Routing engine info/serial number etc. are not populated with correct information in device facts from device running Junos Evolution. This issue seem to only affect Modular chassis. 

This is with junos-eznc 2.6.1

**Example output from Modular Chassis running Junos Evo device:**

```
>>> dev.facts
{'2RE': None,            >>>> NoneType returned
 'HOME': '/var/home/XXXXXXXX',
 'RE0': None,            >>>> NoneType returned
 'RE1': None,            >>>> NoneType returned
 'RE_hw_mi': None,  
 'current_re': ['re0'],
 'domain': 'XXXXXXXX',
 'fqdn': 'XXXXXXXX',
 'hostname': 'XXXXXXXX',
 'hostname_info': {'re0': 'XXXXXXXX',
                   're1': 'XXXXXXXX'},
 'ifd_style': 'CLASSIC',
 'junos_info': {'re0': {'object': junos.version_info(major=(20, 4), type=R, minor=2-S2, build=2-S2),
                        'text': '20.4R2-S2.9-EVO limited'},
                're1': {'object': junos.version_info(major=(20, 4), type=R, minor=2-S2, build=2-S2),
                        'text': '20.4R2-S2.9-EVO limited'}},
 'master': None,          >>>> NoneType returned
 'model': 'PTX10008',
 'model_info': {'re0': 'PTX10008', 're1': 'PTX10008'},
 'personality': None,
 're_info': None,          >>>> NoneType returned
 're_master': None,      >>>> NoneType returned
 'serialnumber': None, >>>> NoneType returned
 'srx_cluster': None,
 'srx_cluster_id': None,
 'srx_cluster_redundancy_group': None,
 'switch_style': 'VLAN_L2NG',
 'vc_capable': False,
 'vc_fabric': None,
 'vc_master': None,
 'vc_mode': None,
 'version': '20.4R2-S2.9-EVO limited',
 'version_RE0': '20.4R2-S2.9-EVO limited',
 'version_RE1': '20.4R2-S2.9-EVO limited',
 'version_info': junos.version_info(major=(20, 4), type=R, minor=2-S2, build=2-S2),
 'virtual': None}
```

**Example output from FreeBSD Junos device:**

```
>>> dev.facts
{'2RE': True,
 'HOME': '/var/home/XXXXXXXX',
 'RE0': {'last_reboot_reason': '0x1:power cycle/failure',
         'mastership_state': 'master',
         'model': 'RE-S-2X00x6',
         'status': 'OK',
         'up_time': '19 hours, 50 minutes, 29 seconds'},
 'RE1': {'last_reboot_reason': '0x1:power cycle/failure',
         'mastership_state': 'backup',
         'model': 'RE-S-2X00x6',
         'status': 'OK',
         'up_time': '19 hours, 50 minutes, 31 seconds'},
 'RE_hw_mi': False,
 'current_re': ['re0', 'master', 'node', 'fwdd', 'member', 'pfem'],
 'domain': 'XXXXXXXX',
 'fqdn': 'XXXXXXXX',
 'hostname': 'XXXXXXXX',
 'hostname_info': {'re0': 'XXXXXXXX', 're1': 'XXXXXXXX'},
 'ifd_style': 'CLASSIC',
 'junos_info': {'re0': {'object': junos.version_info(major=(20, 2), type=R, minor=3, build=9),
                        'text': '20.2R3.9'},
                're1': {'object': junos.version_info(major=(20, 2), type=R, minor=3, build=9),
                        'text': '20.2R3.9'}},
 'master': 'RE0',
 'model': 'MX960',
 'model_info': {'re0': 'MX960', 're1': 'MX960'},
 'personality': 'MX',
 're_info': {'default': {'0': {'last_reboot_reason': '0x1:power cycle/failure',
                               'mastership_state': 'master',
                               'model': 'RE-S-2X00x6',
                               'status': 'OK'},
                         '1': {'last_reboot_reason': '0x1:power cycle/failure',
                               'mastership_state': 'backup',
                               'model': 'RE-S-2X00x6',
                               'status': 'OK'},
                         'default': {'last_reboot_reason': '0x1:power '
                                                           'cycle/failure',
                                     'mastership_state': 'master',
                                     'model': 'RE-S-2X00x6',
                                     'status': 'OK'}}},
 're_master': {'default': '0'},
 'serialnumber': 'XXXXXXXX',
 'srx_cluster': None,
 'srx_cluster_id': None,
 'srx_cluster_redundancy_group': None,
 'switch_style': 'BRIDGE_DOMAIN',
 'vc_capable': False,
 'vc_fabric': None,
 'vc_master': None,
 'vc_mode': None,
 'version': '20.2R3.9',
 'version_RE0': '20.2R3.9',
 'version_RE1': '20.2R3.9',
 'version_info': junos.version_info(major=(20, 2), type=R, minor=3, build=9),
 'virtual': False}
```

**Example output from Fixed Chassis running Junos Evo:**

```
>>> dev.facts
{'2RE': False,
 'HOME': '/var/home/XXXXXXXX',
 'RE0': {'last_reboot_reason': 'power cycle',
         'mastership_state': 'Master',
         'model': 'RE-JNP10003-160C',
         'status': 'OK',
         'up_time': '21 hours, 15 minutes, 54 seconds'},
 'RE1': None,
 'RE_hw_mi': False,
 'current_re': ['re0'],
 'domain': 'XXXXXXXX',
 'fqdn': 'XXXXXXXX',
 'hostname': 'XXXXXXXX',
 'hostname_info': {'re0': 'XXXXXXXX'},
 'ifd_style': 'CLASSIC',
 'junos_info': {'re0': {'object': junos.version_info(major=(19, 4), type=R, minor=2, build=2),
                        'text': '19.4R2.4-EVO'}},
 'master': 'RE0',
 'model': 'PTX10003-160C',
 'model_info': {'re0': 'PTX10003-160C'},
 'personality': 'PTX',
 're_info': {'default': {'0': {'last_reboot_reason': 'power cycle',
                               'mastership_state': 'Master',
                               'model': 'RE-JNP10003-160C',
                               'status': 'OK'},
                         'default': {'last_reboot_reason': 'power cycle',
                                     'mastership_state': 'Master',
                                     'model': 'RE-JNP10003-160C',
                                     'status': 'OK'}}},
 're_master': {'default': '0'},
 'serialnumber': 'XXXXXXXX',
 'srx_cluster': None,
 'srx_cluster_id': None,
 'srx_cluster_redundancy_group': None,
 'switch_style': 'VLAN_L2NG',
 'vc_capable': False,
 'vc_fabric': None,
 'vc_master': None,
 'vc_mode': None,
 'version': '19.4R2.4-EVO',
 'version_RE0': '19.4R2.4-EVO',
 'version_RE1': None,
 'version_info': junos.version_info(major=(19, 4), type=R, minor=2, build=2),
 'virtual': False}
```

**Comment by rahuluk86** [comment]
It doesn't look like a PyEZ issue. The XML returned by device seems to have an invalid URI when we use limited s/w version.

```
>>> rsp = dev.rpc.get_route_engine_information(normalize=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/jnpr/junos/rpcmeta.py", line 364, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/usr/local/lib/python3.6/dist-packages/jnpr/junos/decorators.py", line 63, in wrapper
    result = function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jnpr/junos/decorators.py", line 31, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jnpr/junos/device.py", line 837, in execute
    filter_xml=kvargs.get("filter_xml"),
  File "/usr/local/lib/python3.6/dist-packages/jnpr/junos/decorators.py", line 117, in wrapper
    rsp = function(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jnpr/junos/device.py", line 1440, in _rpc_reply
    return self._conn.rpc(rpc_cmd_e, filter_xml)._NCElement__doc
  File "/usr/local/lib/python3.6/dist-packages/ncclient/manager.py", line 231, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/ncclient/operations/third_party/juniper/rpc.py", line 52, in request
    return self._request(rpc)
  File "/usr/local/lib/python3.6/dist-packages/ncclient/operations/rpc.py", line 350, in _request
    self._reply.parse()
  File "/usr/local/lib/python3.6/dist-packages/ncclient/operations/rpc.py", line 160, in parse
    root = self._root = to_ele(self._raw, huge_tree=self._huge_tree) # The <rpc-reply> element
  File "/usr/local/lib/python3.6/dist-packages/ncclient/xml_.py", line 124, in to_ele
    return x if etree.iselement(x) else etree.fromstring(x.encode('UTF-8'), parser=_get_parser(huge_tree))
  File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1784, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 2
lxml.etree.XMLSyntaxError: xmlns: 'http://xml.juniper.net/junos/20.4R2-S2.9-EVO limited/junos-chassis' is not a valid URI, line 2, column 101
```
