### ISSUE TITLE
Failure parsing ASN in AS-dot notation

### ISSUE THREAD

**Issue by gmazoyer** [Juniper/py-junos-eznc#1150]
I have recently faced an issue where a Juniper MX was returning peer AS for some BGP sessions in the AS-dot notation. My code was was therefore failing because it appears that the parsing of an ASN in AS-dot notation does not work. See the following stack trace:

```
Traceback (most recent call last):
  File "/opt/peering-manager/venv/lib/python3.7/site-packages/jnpr/junos/factory/view.py", line 315, in __getattr__
    return _munch(found[0])
  File "/opt/peering-manager/venv/lib/python3.7/site-packages/jnpr/junos/factory/view.py", line 312, in _munch
    return astype(as_str)
ValueError: invalid literal for int() with base 10: '1.2345'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
<redacted lots of internal code>
  File "/opt/peering-manager/venv/lib/python3.7/site-packages/napalm/junos/junos.py", line 1533, in get_bgp_neighbors_detail
    instance=instance, neighbor_address=str(neighbor_address)
  File "/opt/peering-manager/venv/lib/python3.7/site-packages/jnpr/junos/factory/table.py", line 190, in items
    return list(zip(self.keys(), self.values()))
  File "/opt/peering-manager/venv/lib/python3.7/site-packages/jnpr/junos/factory/table.py", line 182, in values
    return [list(this.items()) for this in self]
  File "/opt/peering-manager/venv/lib/python3.7/site-packages/jnpr/junos/factory/table.py", line 182, in <listcomp>
    return [list(this.items()) for this in self]
  File "/opt/peering-manager/venv/lib/python3.7/site-packages/jnpr/junos/factory/view.py", line 157, in items
    return zip(self.keys(), self.values())
  File "/opt/peering-manager/venv/lib/python3.7/site-packages/jnpr/junos/factory/view.py", line 153, in values
    return [getattr(self, field) for field in self.keys()]
  File "/opt/peering-manager/venv/lib/python3.7/site-packages/jnpr/junos/factory/view.py", line 153, in <listcomp>
    return [getattr(self, field) for field in self.keys()]
  File "/opt/peering-manager/venv/lib/python3.7/site-packages/jnpr/junos/factory/view.py", line 323, in __getattr__
    raise RuntimeError("Unable to handle field:'%s'" % name)
RuntimeError: Unable to handle field:'remote_as'
```

On the MX itself, looking at the `show bgp neighbor` output we see:

```
Peer: <peer ip>+179 AS 1.2345 Local: <local ip>+65521 AS <local AS>
```

As the stack trace shows, the code fails to parse the string `1.2345` as an integer. I think that there are two options here to fix this issue since Junos allows ASN in AS-dot notation:

1. Keep the ASN as a string in AS-dot notation
2. Convert the ASN as a integer but with a slightly different method (attached below)

```python
asn = "1.2345"
big, little = asn.split(".")
result = (int(big) << 16) + int(little)
print(result)
67881
```

IMO the second option is the best from an automation point of view as we tend to prefer integer value where possible and it will avoid people to write their own conversion code. And lets face it most of us use ASN as a single 32/64 bit integer instead of their AS-dot representation.

**Comment by gmazoyer** [comment]
@dineshbaburam91 here is an example `show bgp neighbor | display xml` output

```xml
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/19.4R0/junos">
    <bgp-information xmlns="http://xml.juniper.net/junos/19.4R0/junos-routing">
        <bgp-peer junos:style="detail">
            <peer-address>192.0.2.1</peer-address>
            <peer-as>1.5432</peer-as>
            <local-address>unspecified</local-address>
            <local-as>1.2345</local-as>
            <peer-group>test</peer-group>
            <peer-cfg-rti>master</peer-cfg-rti>
            <peer-fwd-rti>master</peer-fwd-rti>
            <peer-type>External</peer-type>
            <peer-state>Idle</peer-state>
            <peer-flags>PeerInterfaceError</peer-flags>
            <last-state>NoState</last-state>
            <last-event>NoEvent</last-event>
            <last-error>None</last-error>
            <bgp-option-information xmlns="http://xml.juniper.net/junos/19.4R0/junos-routing">
                <bgp-options>Preference PeerAS Refresh</bgp-options>
                <bgp-options2></bgp-options2>
                <bgp-options-extended>GracefulShutdownRcv</bgp-options-extended>
                <holdtime>90</holdtime>
                <preference>170</preference>
                <gshut-recv-local-preference>0</gshut-recv-local-preference>
            </bgp-option-information>
            <flap-count>0</flap-count>
        </bgp-peer>
    </bgp-information>
    <cli>
        <banner>[edit]</banner>
    </cli>
</rpc-reply>
```

And the configuration used to reproduce it.

```
routing-options {
    autonomous-system 1.2345 asdot-notation;
}
protocols {
    bgp {
        group test {
            neighbor 192.0.2.1 {
                peer-as 1.5432;
            }
        }
    }
}
```

**Comment by dineshbaburam91** [comment]
@gmazoyer  I am not seeing this issue in the latest PyEZ release.

```
yaml_data = """
---
bgpTable:
    rpc: get-bgp-neighbor-information
    item: bgp-peer
    key: peer-address 
    view: bgpView
bgpView:
    fields:
        local_as: local-as
        peer_as: peer-as
        local_address: local-address
"""

globals().update(FactoryLoader().load(yaml.load(yaml_data,
                                                Loader=yamlordereddictloader.Loader)))
with Device(host='x.x.x.x', user='XXXX', password='XXXX', port=22) as dev:

    stats = bgpTable(dev).get()
    pprint(json.loads(stats.to_json()))
```

Output:
{'192.0.2.1': {'local_address': 'unspecified',
               'local_as': '1.2345',
               'peer_as': '1.5432'}}

**Comment by dineshbaburam91** [comment]
The issue is not seen in the latest PyEZ release. I will close the ticket
