### ISSUE TITLE
Unit Test fails with lxml lxml-4.8.0

### ISSUE THREAD

**Issue by balasankarrajaguru** [Juniper/py-junos-eznc#1157]
Issue : 
root@8dc26d52d0d6:/content/tmp/pyez/tests/unit# nosetests -v tests.unit.factory.test_table.TestFactoryTable
test_config_constructor (tests.unit.factory.test_table.TestFactoryTable) ... ok
test_table_hostname (tests.unit.factory.test_table.TestFactoryTable) ... ok
test_table_is_container (tests.unit.factory.test_table.TestFactoryTable) ... ok
test_table_repr_xml_none (tests.unit.factory.test_table.TestFactoryTable) ... ok
test_table_view_setter_ValueError (tests.unit.factory.test_table.TestFactoryTable) ... ok
test_table_get_return_none (tests.unit.factory.test_table.TestFactoryTable) ... ok
test_table_get_RuntimeError (tests.unit.factory.test_table.TestFactoryTable) ... ok
test_keys_RuntimeError (tests.unit.factory.test_table.TestFactoryTable) ... ok
test_keys__keys_composite (tests.unit.factory.test_table.TestFactoryTable) ... ok
test_keys__keys_pipe (tests.unit.factory.test_table.TestFactoryTable) ... ok
test_table__contains__ (tests.unit.factory.test_table.TestFactoryTable) ... ok
test_table__getitem__ (tests.unit.factory.test_table.TestFactoryTable) ... ok
test_table__getitem__slice (tests.unit.factory.test_table.TestFactoryTable) ... ok
test_table__getitem__tuple (tests.unit.factory.test_table.TestFactoryTable) ... ok
test_table_get_keys_values (tests.unit.factory.test_table.TestFactoryTable) ... ok
test_table_items (tests.unit.factory.test_table.TestFactoryTable) ... ok
test_table_repr_xml_not_none (tests.unit.factory.test_table.TestFactoryTable) ... ok
test_table_savexml (tests.unit.factory.test_table.TestFactoryTable) ... ERROR======================================================================
ERROR: test_table_savexml (tests.unit.factory.test_table.TestFactoryTable)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/mock/mock.py", line 1369, in patched
return func(*newargs, **newkeywargs)
File "/content/tmp/pyez/tests/unit/factory/test_table.py", line 145, in test_table_savexml
self.ppt.savexml("/vasr/tmssp/foo.xml", hostname=True, append="test")
File "/content/tmp/pyez/lib/jnpr/junos/factory/table.py", line 248, in savexml
return etree.ElementTree(self.xml).write(open(path, "wb"))
File "src/lxml/etree.pyx", line 2072, in lxml.etree._ElementTree.write
File "src/lxml/serializer.pxi", line 747, in lxml.etree._tofilelike
File "src/lxml/serializer.pxi", line 815, in lxml.etree._create_output_buffer
File "src/lxml/serializer.pxi", line 805, in lxml.etree._create_output_buffer
FileNotFoundError: [Errno 2] No such file or directory
-------------------- >> begin captured logging << --------------------
ncclient.transport.session: DEBUG: [host None session 0x7f934f7e1438] <SSHSession(session, initial daemon)> created: client_capabilities=<dict_keyiterator object at 0x7f934f8658b8>
ncclient.transport.ssh: DEBUG: [host None session 0x7f934f7e1438] installing listener <jnpr.junos.device.DeviceSessionListener object at 0x7f934f7e1b70>
--------------------- >> end captured logging << -------------------------------------------------------------------------------------------
Ran 18 tests in 0.045sFAILED (errors=1)
root@8dc26d52d0d6:/content/tmp/pyez/tests/unit#

It works fine with lxml-4.7.0

**Comment by dineshbaburam91** [comment]
This issue got fixed using pull request https://github.com/Juniper/py-junos-eznc/pull/1159
