### ISSUE TITLE
make test fails when installed on python 3.9

### ISSUE THREAD

**Issue by sharanyabhat** [Juniper/py-junos-eznc#1165]
``` 

======================================================================
FAIL: test_sw_put_ftp (tests.unit.utils.test_sw.TestSW)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/content/.tox/unittest/lib/python3.9/site-packages/mock/mock.py", line 1346, in patched
    return func(*newargs, **newkeywargs)
  File "/content/tmp/pyez/tests/unit/utils/test_sw.py", line 164, in test_sw_put_ftp
    self.assertTrue(call("test.tgz", "/var/tmp") in mock_ftp_put.mock_calls)
AssertionError: False is not true
-------------------- >> begin captured logging << --------------------
ncclient.transport.session: DEBUG: [host None session 0x7fc7ab1241f0] <SSHSession(session, initial daemon)> created: client_capabilities=<dict_keyiterator object at 0x7fc7ab0f8090>
ncclient.transport.ssh: DEBUG: [host None session 0x7fc7ab1241f0] installing listener <jnpr.junos.device.DeviceSessionListener object at 0x7fc7ab08a910>
ncclient.transport.ssh: DEBUG: [host None session 0x7fc7ab1241f0] installing listener <ncclient.operations.rpc.RPCReplyListener object at 0x7fc7ab0f5040>
--------------------- >> end captured logging 

<< ---------------------
```
Full logs:
[pyez-test-logs.txt](https://github.com/Juniper/py-junos-eznc/files/8440133/pyez-test-logs.txt)

Currently, there is no support for python 3.9 .  Will python 3.9 be supported in next release?

**Comment by dineshbaburam91** [comment]
Fixed #1170
