### ISSUE TITLE
Using connection: juniper.device.pyez with mode: serial tries to resolve ansible_inventory_name

### ISSUE THREAD

**Issue by ahussey-redhat** [Juniper/py-junos-eznc#1180]
Issue Type
------
 - Bug Report

cross posting with https://github.com/Juniper/ansible-junos-stdlib/issues/584

Module Name
------
juniper.device.pyez
juniper.device.config

juniper.device collection and Python libraries version
```
# pip freeze
junos-eznc==2.6.3

# /home/HUSSDOGG.com/alex/.ansible/collections/ansible_collections
Collection              Version
----------------------- -------
juniper.device          1.0.1 

# ansible --version
ansible [core 2.12.5]
  config file = /home/HUSSDOGG.com/alex/Documents/code/ansible/playbooks/network_bootstrap/ansible.cfg
  configured module search path = ['/home/HUSSDOGG.com/alex/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/HUSSDOGG.com/alex/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 12.0.1 20220308 (Red Hat 12.0.1-0)]
  jinja version = 3.0.3
  libyaml = True
```

OS / Environment
------

```
Model: srx320
Junos: 15.1X49-D70.3
JUNOS Software Release [15.1X49-D70.3]
```
Summary
------
When using the connection type `juniper.device.pyez` and the mode `serial`, if the hostname fails to resolve the module fails.

Steps to reproduce
------
```yaml
---
- name: Bootstrap a JUNOS network device
  hosts: all
  become: true
  gather_facts: false
  vars:
    mode: serial
    user: root
    password: abc123
  tasks:
    - name: Retrieve current configuration to allow rollback
      juniper.device.config:
        retrieve: committed
        dest_dir: configs/backups
        format: set
```

Expected results
```bash
TASK [Retrieve current configuration to allow rollback] ***************************************************************************************
 ok: [hussfw02.hussdogg.com] => changed=false 
  ...(output cont.)
 msg: 'Configuration has been: opened, retrieved, closed.'
```
Actual results
------
```bash
TASK [Retrieve current configuration to allow rollback] ***************************************************************************************
task path: /home/HUSSDOGG.com/alex/Documents/code/ansible/playbooks/network_bootstrap/playbook_configure_srx.yml:7
<hussfw02.hussdogg.com> ESTABLISH LOCAL CONNECTION FOR USER: alex@HUSSDOGG.com
<hussfw02.hussdogg.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/HUSSDOGG.com/alex/.ansible/tmp/ansible-local-83013iz1qpefm `"&& mkdir "` echo /home/HUSSDOGG.com/alex/.ansible/tmp/ansible-local-83013iz1qpefm/ansible-tmp-1652745563.9289007-83043-102300553468997 `" && echo ansible-tmp-1652745563.9289007-83043-102300553468997="` echo /home/HUSSDOGG.com/alex/.ansible/tmp/ansible-local-83013iz1qpefm/ansible-tmp-1652745563.9289007-83043-102300553468997 `" ) && sleep 0'
Using module file /home/HUSSDOGG.com/alex/.ansible/collections/ansible_collections/juniper/device/plugins/modules/config.py
<hussfw02.hussdogg.com> PUT /home/HUSSDOGG.com/alex/.ansible/tmp/ansible-local-83013iz1qpefm/tmpsubcdlo2 TO /home/HUSSDOGG.com/alex/.ansible/tmp/ansible-local-83013iz1qpefm/ansible-tmp-1652745563.9289007-83043-102300553468997/AnsiballZ_config.py
<hussfw02.hussdogg.com> EXEC /bin/sh -c 'chmod u+x /home/HUSSDOGG.com/alex/.ansible/tmp/ansible-local-83013iz1qpefm/ansible-tmp-1652745563.9289007-83043-102300553468997/ /home/HUSSDOGG.com/alex/.ansible/tmp/ansible-local-83013iz1qpefm/ansible-tmp-1652745563.9289007-83043-102300553468997/AnsiballZ_config.py && sleep 0'
<hussfw02.hussdogg.com> EXEC /bin/sh -c '/usr/bin/python3 /home/HUSSDOGG.com/alex/.ansible/tmp/ansible-local-83013iz1qpefm/ansible-tmp-1652745563.9289007-83043-102300553468997/AnsiballZ_config.py && sleep 0'
<hussfw02.hussdogg.com> EXEC /bin/sh -c 'rm -f -r /home/HUSSDOGG.com/alex/.ansible/tmp/ansible-local-83013iz1qpefm/ansible-tmp-1652745563.9289007-83043-102300553468997/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/HUSSDOGG.com/alex/.ansible/tmp/ansible-local-83013iz1qpefm/ansible-tmp-1652745563.9289007-83043-102300553468997/AnsiballZ_config.py", line 107, in <module>
    _ansiballz_main()
  File "/home/HUSSDOGG.com/alex/.ansible/tmp/ansible-local-83013iz1qpefm/ansible-tmp-1652745563.9289007-83043-102300553468997/AnsiballZ_config.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/HUSSDOGG.com/alex/.ansible/tmp/ansible-local-83013iz1qpefm/ansible-tmp-1652745563.9289007-83043-102300553468997/AnsiballZ_config.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.juniper.device.plugins.modules.config', init_globals=dict(_module_fqn='ansible_collections.juniper.device.plugins.modules.config', _modlib_path=modlib_path),
  File "/usr/lib64/python3.10/runpy.py", line 209, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_juniper.device.config_payload_dukbf2_m/ansible_juniper.device.config_payload.zip/ansible_collections/juniper/device/plugins/modules/config.py", line 1164, in <module>
  File "/tmp/ansible_juniper.device.config_payload_dukbf2_m/ansible_juniper.device.config_payload.zip/ansible_collections/juniper/device/plugins/modules/config.py", line 777, in main
  File "/tmp/ansible_juniper.device.config_payload_dukbf2_m/ansible_juniper.device.config_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py", line 620, in __init__
  File "/tmp/ansible_juniper.device.config_payload_dukbf2_m/ansible_juniper.device.config_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py", line 681, in get_connection
  File "/tmp/ansible_juniper.device.config_payload_dukbf2_m/ansible_juniper.device.config_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py", line 697, in get_capabilities
  File "/tmp/ansible_juniper.device.config_payload_dukbf2_m/ansible_juniper.device.config_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
ansible.module_utils.connection.ConnectionError: Unable to make a PyEZ connection: ConnectUnknownHostError(hussfw02.hussdogg.com)
fatal: [hussfw02.hussdogg.com]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/HUSSDOGG.com/alex/.ansible/tmp/ansible-local-83013iz1qpefm/ansible-tmp-1652745563.9289007-83043-102300553468997/AnsiballZ_config.py", line 107, in <module>
        _ansiballz_main()
      File "/home/HUSSDOGG.com/alex/.ansible/tmp/ansible-local-83013iz1qpefm/ansible-tmp-1652745563.9289007-83043-102300553468997/AnsiballZ_config.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/HUSSDOGG.com/alex/.ansible/tmp/ansible-local-83013iz1qpefm/ansible-tmp-1652745563.9289007-83043-102300553468997/AnsiballZ_config.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.juniper.device.plugins.modules.config', init_globals=dict(_module_fqn='ansible_collections.juniper.device.plugins.modules.config', _modlib_path=modlib_path),
      File "/usr/lib64/python3.10/runpy.py", line 209, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib64/python3.10/runpy.py", line 96, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_juniper.device.config_payload_dukbf2_m/ansible_juniper.device.config_payload.zip/ansible_collections/juniper/device/plugins/modules/config.py", line 1164, in <module>
      File "/tmp/ansible_juniper.device.config_payload_dukbf2_m/ansible_juniper.device.config_payload.zip/ansible_collections/juniper/device/plugins/modules/config.py", line 777, in main
      File "/tmp/ansible_juniper.device.config_payload_dukbf2_m/ansible_juniper.device.config_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py", line 620, in __init__
      File "/tmp/ansible_juniper.device.config_payload_dukbf2_m/ansible_juniper.device.config_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py", line 681, in get_connection
      File "/tmp/ansible_juniper.device.config_payload_dukbf2_m/ansible_juniper.device.config_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py", line 697, in get_capabilities
      File "/tmp/ansible_juniper.device.config_payload_dukbf2_m/ansible_juniper.device.config_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
    ansible.module_utils.connection.ConnectionError: Unable to make a PyEZ connection: ConnectUnknownHostError(hussfw02.hussdogg.com)
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

**Comment by dineshbaburam91** [comment]
@ahussey-redhat as per the comment on 
https://github.com/Juniper/ansible-junos-stdlib/issues/584 , it is expected behavior.

Closing the ticket
