### ISSUE TITLE
utils.sw.install gives int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by Aaron-MJohn** [Juniper/py-junos-eznc#1184]
I am trying to upgrade the EX2300 with 48 POE+ switch using below code. I don't set any time out parameters in install function. Everything is using the default value.

```
with Device(host=hostname, user=junos_username, passwd=junos_password) as dev:
        print("Connecting to {}".format(hostname))
        if dev.connected:
            print("Device connected")
            sw = SW(dev)`
            ok = sw.install(
                package=firware_update_files,
                progress=my_progress,
                no_copy=True,
                validate=False,
                cleanfs=True,
            )
```
I get this exception 

```
192.168.1.2:request-package-checks-pending-install rpc is not supported on given device
192.168.1.2:installing software ... please be patient ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jnpr/junos/device.py", line 227, in timeout
    self._conn.timeout = int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jnpr/junos/decorators.py", line 24, in wrapper
    dev.timeout = restore_timeout
  File "/usr/local/lib/python3.8/dist-packages/jnpr/junos/device.py", line 229, in timeout
    raise RuntimeError(
RuntimeError: could not convert timeout value of None to an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jnpr/junos/device.py", line 227, in timeout
    self._conn.timeout = int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/..../devel/ros_ws/src/bg_sandbox/juno_config/scripts/juno_update.py", line 62, in <module>
    main()
  File "/home/..../devel/ros_ws/src/bg_sandbox/juno_config/scripts/juno_update.py", line 37, in main
    ok = sw.install(
  File "/usr/local/lib/python3.8/dist-packages/jnpr/junos/utils/sw.py", line 990, in install
    add_ok = self.pkgadd(
  File "/usr/local/lib/python3.8/dist-packages/jnpr/junos/utils/sw.py", line 240, in pkgadd
    rsp = self.rpc.request_package_add(**args)
  File "/usr/local/lib/python3.8/dist-packages/jnpr/junos/rpcmeta.py", line 364, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/usr/local/lib/python3.8/dist-packages/jnpr/junos/decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jnpr/junos/decorators.py", line 27, in wrapper
    dev.timeout = restore_timeout
  File "/usr/local/lib/python3.8/dist-packages/jnpr/junos/device.py", line 229, in timeout
    raise RuntimeError(
RuntimeError: could not convert timeout value of None to an integer
```

**Comment by francoisv100** [comment]
related error
getting the following error for device timeout as well , when using version 2.6.4 , version 2.6.3 works correctly,

Python code:
rpc = dev.rpc.get_interface_information(dev_timeout=360, level_extra='descriptions') 

Error below for version 2.6.4:

Traceback (most recent call last):
  File "/Users/francoisvanheerden/PycharmProjects/venv/lib/python3.7/site-packages/jnpr/junos/device.py", line 227, in timeout
    self._conn.timeout = int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/francoisvanheerden/PycharmProjects/venv/lib/python3.7/site-packages/jnpr/junos/decorators.py", line 24, in wrapper
    dev.timeout = restore_timeout
  File "/Users/francoisvanheerden/PycharmProjects/venv/lib/python3.7/site-packages/jnpr/junos/device.py", line 230, in timeout
    "could not convert timeout value of %s to an " "integer" % (value)
RuntimeError: could not convert timeout value of None to an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/francoisvanheerden/PycharmProjects/venv/lib/python3.7/site-packages/jnpr/junos/device.py", line 227, in timeout
    self._conn.timeout = int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./junos-ez-interface-description-account-no-only.py", line 41, in <module>
    rpc = dev.rpc.get_interface_information(dev_timeout="360", level_extra='descriptions')
  File "/Users/francoisvanheerden/PycharmProjects/venv/lib/python3.7/site-packages/jnpr/junos/rpcmeta.py", line 364, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/Users/francoisvanheerden/PycharmProjects/venv/lib/python3.7/site-packages/jnpr/junos/decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "/Users/francoisvanheerden/PycharmProjects/venv/lib/python3.7/site-packages/jnpr/junos/decorators.py", line 27, in wrapper
    dev.timeout = restore_timeout
  File "/Users/francoisvanheerden/PycharmProjects/venv/lib/python3.7/site-packages/jnpr/junos/device.py", line 230, in timeout
    "could not convert timeout value of %s to an " "integer" % (value)
RuntimeError: could not convert timeout value of None to an integer

**Comment by chidanandpujar** [comment]
Hi,

Please try with option dev.timeout .

from jnpr.junos import Device
from lxml import etree

dev = Device(host='xx.xx.xx.xx', user='xyz', password='xyz', gather_facts=False)
dev.open()
dev.timeout = 360
op = dev.rpc.get_interface_information(dev_timeout=360)
print (etree.tostring(op))
dev.close()


Thanks & Regards
Chidanand

**Comment by Aaron-MJohn** [comment]
Yes setting device.time solved the issue. Thanks

**Comment by chidanandpujar** [comment]
Issue fixed via commit https://github.com/Juniper/py-junos-eznc/pull/1192

**Comment by Bischoff** [comment]
Thanks @chidanandpujar . I was also getting it from junos salt-proxy when trying to apply a Salt state.
