### ISSUE TITLE
Timeout value on connection does not work 

### ISSUE THREAD

**Issue by jrome011** [Juniper/py-junos-eznc#1200]
Hello,

I have a script that runs the following to upgrade devices: 
`     
ok, msg = sw.install(
package=pckg_image, validate=False, progress=myprogress, timeout=900, checksum_timeout=400
)
`

But get the following Traceback:

`
Traceback (most recent call last):
  File "/Users/gama/Repos/devnet/legacy_upgrades/.venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/Users/gama/Repos/devnet/legacy_upgrades/upgrade_legacy.py", line 124, in junos_upgrade
    ok, msg = sw.install(
  File "/Users/gama/Repos/devnet/legacy_upgrades/.venv/lib/python3.9/site-packages/jnpr/junos/utils/sw.py", line 990, in install
    add_ok = self.pkgadd(
  File "/Users/gama/Repos/devnet/legacy_upgrades/.venv/lib/python3.9/site-packages/jnpr/junos/utils/sw.py", line 240, in pkgadd
    rsp = self.rpc.request_package_add(**args)
  File "/Users/gama/Repos/devnet/legacy_upgrades/.venv/lib/python3.9/site-packages/jnpr/junos/rpcmeta.py", line 364, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/Users/gama/Repos/devnet/legacy_upgrades/.venv/lib/python3.9/site-packages/jnpr/junos/decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "/Users/gama/Repos/devnet/legacy_upgrades/.venv/lib/python3.9/site-packages/jnpr/junos/decorators.py", line 27, in wrapper
    dev.timeout = restore_timeout
  File "/Users/gama/Repos/devnet/legacy_upgrades/.venv/lib/python3.9/site-packages/jnpr/junos/device.py", line 230, in timeout
    raise RuntimeError(
RuntimeError: could not convert timeout value of None to an integer
`

According to the developer's guide on Page 107 https://www.juniper.net/documentation/us/en/software/junos-pyez/junos-pyez-developer/junos-pyez-developer.pdf this is the right way of setting the timeouts but somehow is being passed on with a value of None or not being set at all?

**Comment by Aaron-MJohn** [comment]
This looks like similar issue i had. https://github.com/Juniper/py-junos-eznc/issues/1184

**Comment by jrome011** [comment]
Thank you @Aaron-MJohn looks like PR #1192 fixed the issue for me too.
