### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'MutableMapping'

### ISSUE THREAD

**Issue by psagrera** [Juniper/py-junos-eznc#1227]
I've got the following error in python3.10 

```
 Traceback (most recent call last):
  File "/source/data/input-netconf.py", line 10, in <module>
    from jnpr.junos import *
  File "/usr/lib/python3.10/site-packages/jnpr/junos/__init__.py", line 1, in <module>
    from jnpr.junos.device import Device
  File "/usr/lib/python3.10/site-packages/jnpr/junos/device.py", line 29, in <module>
    from jnpr.junos.factcache import _FactCache
  File "/usr/lib/python3.10/site-packages/jnpr/junos/factcache.py", line 10, in <module>
    class _FactCache(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```
To solve this error I've done the following in that file 

**/usr/lib/python3.10/site-packages/jnpr/junos/factcache.py**
```
import sys
if sys.version_info.major == 3 and sys.version_info.minor >= 10:
    from collections.abc import MutableMapping
else:
    from collections import MutableMapping
```

**Comment by psagrera** [comment]
Sorry, I was running and old version of the library
