### ISSUE TITLE
python 3.10 support for PyEZ

### ISSUE THREAD

**Issue by spithavath** [Juniper/py-junos-eznc#1253]
Testing Python 3.10 support for PyEZ

**Comment by chidanandpujar** [comment]
with nose2 we are seeing multiple errors , we are looking into it .

```
======================================================================
ERROR: test_sw_info_bsys (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_get_software_information.py", line 171, in test_sw_info_bsys
    self.assertEqual(self.dev.facts["hostname"], "bsys")
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 119, in __getitem__
    raise RuntimeError(
RuntimeError: The jnpr.junos.facts.get_software_information module returned the model fact, but does not list model as a provided fact. Please report this error.

======================================================================
ERROR: test_sw_info_dual (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_get_software_information.py", line 104, in test_sw_info_dual
    self.assertEqual(self.dev.facts["junos_info"]["re0"]["text"], "15.1F5.15-C1.12")
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 119, in __getitem__
    raise RuntimeError(
RuntimeError: The jnpr.junos.facts.get_software_information module returned the model fact, but does not list model as a provided fact. Please report this error.

======================================================================
ERROR: test_sw_info_dual_other_re_off (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_get_software_information.py", line 117, in test_sw_info_dual_other_re_off
    self.dev.facts["junos_info"]["re1"]["text"], "18.3I20180716_1639"
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 119, in __getitem__
    raise RuntimeError(
RuntimeError: The jnpr.junos.facts.get_software_information module returned the model fact, but does not list model as a provided fact. Please report this error.

======================================================================
ERROR: test_sw_info_err (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_get_software_information.py", line 285, in test_sw_info_err
    self.assertEqual(self.dev.facts["model"], None)
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 95, in __getitem__
    new_facts = self._callbacks[key](self._device)
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/facts/personality.py", line 24, in get_facts
    model = device.facts["model"]
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 84, in __getitem__
    raise jnpr.junos.exception.FactLoopError(
jnpr.junos.exception.FactLoopError: A loop was detected while gathering the model fact. The jnpr.junos.facts.personality module has already been called. Please report this error.

======================================================================
ERROR: test_sw_info_ex (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_get_software_information.py", line 139, in test_sw_info_ex
    self.assertEqual(self.dev.facts["junos_info"]["re0"]["text"], "11.4R1.6")
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 119, in __getitem__
    raise RuntimeError(
RuntimeError: The jnpr.junos.facts.get_software_information module returned the model fact, but does not list model as a provided fact. Please report this error.

======================================================================
ERROR: test_sw_info_gnf (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_get_software_information.py", line 228, in test_sw_info_gnf
    self.assertEqual(self.dev.facts["hostname"], "mgb-gnf-a")
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 119, in __getitem__
    raise RuntimeError(
RuntimeError: The jnpr.junos.facts.get_software_information module returned the model fact, but does not list model as a provided fact. Please report this error.

======================================================================
ERROR: test_sw_info_jdm (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_get_software_information.py", line 201, in test_sw_info_jdm
    self.assertEqual(self.dev.facts["hostname"], "jdm")
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 119, in __getitem__
    raise RuntimeError(
RuntimeError: The jnpr.junos.facts.get_software_information module returned the model fact, but does not list model as a provided fact. Please report this error.

======================================================================
ERROR: test_sw_info_nfx (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_get_software_information.py", line 151, in test_sw_info_nfx
    self.assertEqual(self.dev.facts["hostname"], "jdm")
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 119, in __getitem__
    raise RuntimeError(
RuntimeError: The jnpr.junos.facts.get_software_information module returned the model fact, but does not list model as a provided fact. Please report this error.

======================================================================
ERROR: test_sw_info_no_version (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_get_software_information.py", line 93, in test_sw_info_no_version
    self.assertEqual(self.dev.facts["junos_info"], None)
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 119, in __getitem__
    raise RuntimeError(
RuntimeError: The jnpr.junos.facts.get_software_information module returned the model fact, but does not list model as a provided fact. Please report this error.

======================================================================
ERROR: test_sw_info_simple (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_get_software_information.py", line 75, in test_sw_info_simple
    self.assertEqual(self.dev.facts["junos_info"]["re0"]["text"], "12.3X48-D40.5")
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 119, in __getitem__
    raise RuntimeError(
RuntimeError: The jnpr.junos.facts.get_software_information module returned the model fact, but does not list model as a provided fact. Please report this error.

======================================================================
ERROR: test_sw_info_single (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_get_software_information.py", line 30, in test_sw_info_single
    self.assertEqual(self.dev.facts["junos_info"]["re0"]["text"], "16.1R1.11")
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 119, in __getitem__
    raise RuntimeError(
RuntimeError: The jnpr.junos.facts.get_software_information module returned the model fact, but does not list model as a provided fact. Please report this error.

======================================================================
ERROR: test_sw_info_srx_cluster (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_get_software_information.py", line 256, in test_sw_info_srx_cluster
    self.assertEqual(self.dev.facts["hostname"], "frogbert")
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 119, in __getitem__
    raise RuntimeError(
RuntimeError: The jnpr.junos.facts.get_software_information module returned the model fact, but does not list model as a provided fact. Please report this error.

======================================================================
ERROR: test_sw_info_txp (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_get_software_information.py", line 128, in test_sw_info_txp
    self.assertEqual(self.dev.facts["junos_info"]["re0"]["text"], "13.3R9-S2.1")
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 119, in __getitem__
    raise RuntimeError(
RuntimeError: The jnpr.junos.facts.get_software_information module returned the model fact, but does not list model as a provided fact. Please report this error.

======================================================================
ERROR: test_sw_info_vc (tests.unit.facts.test_get_software_information.TestGetSoftwareInformation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_get_software_information.py", line 47, in test_sw_info_vc
    self.dev.facts["junos_info"]["member0"]["text"], "15.1-20161209.0"
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 119, in __getitem__
    raise RuntimeError(
RuntimeError: The jnpr.junos.facts.get_software_information module returned the model fact, but does not list model as a provided fact. Please report this error.

======================================================================
ERROR: test_personality_m (tests.unit.facts.test_personality.TestPersonality)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_personality.py", line 35, in test_personality_m
    self.assertEqual(self.dev.facts["personality"], "M")
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 95, in __getitem__
    new_facts = self._callbacks[key](self._device)
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/facts/personality.py", line 24, in get_facts
    model = device.facts["model"]
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 84, in __getitem__
    raise jnpr.junos.exception.FactLoopError(
jnpr.junos.exception.FactLoopError: A loop was detected while gathering the model fact. The jnpr.junos.facts.personality module has already been called. Please report this error.

======================================================================
ERROR: test_personality_mx (tests.unit.facts.test_personality.TestPersonality)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_personality.py", line 41, in test_personality_mx
    self.assertEqual(self.dev.facts["personality"], "MX")
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 95, in __getitem__
    new_facts = self._callbacks[key](self._device)
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/facts/personality.py", line 24, in get_facts
    model = device.facts["model"]
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 84, in __getitem__
    raise jnpr.junos.exception.FactLoopError(
jnpr.junos.exception.FactLoopError: A loop was detected while gathering the model fact. The jnpr.junos.facts.personality module has already been called. Please report this error.

======================================================================
ERROR: test_personality_olive (tests.unit.facts.test_personality.TestPersonality)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_personality.py", line 47, in test_personality_olive
    self.assertEqual(self.dev.facts["personality"], "OLIVE")
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 95, in __getitem__
    new_facts = self._callbacks[key](self._device)
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/facts/personality.py", line 24, in get_facts
    model = device.facts["model"]
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 84, in __getitem__
    raise jnpr.junos.exception.FactLoopError(
jnpr.junos.exception.FactLoopError: A loop was detected while gathering the model fact. The jnpr.junos.facts.personality module has already been called. Please report this error.

======================================================================
ERROR: test_personality_ptx (tests.unit.facts.test_personality.TestPersonality)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_personality.py", line 53, in test_personality_ptx
    self.assertEqual(self.dev.facts["personality"], "PTX")
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 95, in __getitem__
    new_facts = self._callbacks[key](self._device)
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/facts/personality.py", line 24, in get_facts
    model = device.facts["model"]
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 84, in __getitem__
    raise jnpr.junos.exception.FactLoopError(
jnpr.junos.exception.FactLoopError: A loop was detected while gathering the model fact. The jnpr.junos.facts.personality module has already been called. Please report this error.

======================================================================
ERROR: test_personality_srx_branch (tests.unit.facts.test_personality.TestPersonality)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_personality.py", line 59, in test_personality_srx_branch
    self.assertEqual(self.dev.facts["personality"], "SRX_BRANCH")
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 95, in __getitem__
    new_facts = self._callbacks[key](self._device)
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/facts/personality.py", line 24, in get_facts
    model = device.facts["model"]
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 84, in __getitem__
    raise jnpr.junos.exception.FactLoopError(
jnpr.junos.exception.FactLoopError: A loop was detected while gathering the model fact. The jnpr.junos.facts.personality module has already been called. Please report this error.

======================================================================
ERROR: test_personality_srx_high_end (tests.unit.facts.test_personality.TestPersonality)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_personality.py", line 71, in test_personality_srx_high_end
    self.assertEqual(self.dev.facts["personality"], "SRX_HIGHEND")
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 95, in __getitem__
    new_facts = self._callbacks[key](self._device)
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/facts/personality.py", line 24, in get_facts
    model = device.facts["model"]
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 84, in __getitem__
    raise jnpr.junos.exception.FactLoopError(
jnpr.junos.exception.FactLoopError: A loop was detected while gathering the model fact. The jnpr.junos.facts.personality module has already been called. Please report this error.

======================================================================
ERROR: test_personality_srx_mid_range (tests.unit.facts.test_personality.TestPersonality)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_personality.py", line 65, in test_personality_srx_mid_range
    self.assertEqual(self.dev.facts["personality"], "SRX_MIDRANGE")
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 95, in __getitem__
    new_facts = self._callbacks[key](self._device)
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/facts/personality.py", line 24, in get_facts
    model = device.facts["model"]
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 84, in __getitem__
    raise jnpr.junos.exception.FactLoopError(
jnpr.junos.exception.FactLoopError: A loop was detected while gathering the model fact. The jnpr.junos.facts.personality module has already been called. Please report this error.

======================================================================
ERROR: test_personality_t (tests.unit.facts.test_personality.TestPersonality)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_personality.py", line 77, in test_personality_t
    self.assertEqual(self.dev.facts["personality"], "T")
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 95, in __getitem__
    new_facts = self._callbacks[key](self._device)
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/facts/personality.py", line 24, in get_facts
    model = device.facts["model"]
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 84, in __getitem__
    raise jnpr.junos.exception.FactLoopError(
jnpr.junos.exception.FactLoopError: A loop was detected while gathering the model fact. The jnpr.junos.facts.personality module has already been called. Please report this error.

======================================================================
ERROR: test_personality_vmx (tests.unit.facts.test_personality.TestPersonality)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_personality.py", line 83, in test_personality_vmx
    self.assertEqual(self.dev.facts["personality"], "MX")
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 95, in __getitem__
    new_facts = self._callbacks[key](self._device)
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/facts/personality.py", line 24, in get_facts
    model = device.facts["model"]
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 84, in __getitem__
    raise jnpr.junos.exception.FactLoopError(
jnpr.junos.exception.FactLoopError: A loop was detected while gathering the model fact. The jnpr.junos.facts.personality module has already been called. Please report this error.

======================================================================
ERROR: test_personality_vptx (tests.unit.facts.test_personality.TestPersonality)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_personality.py", line 135, in test_personality_vptx
    self.assertEqual(self.dev.facts["personality"], "PTX")
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 95, in __getitem__
    new_facts = self._callbacks[key](self._device)
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/facts/personality.py", line 24, in get_facts
    model = device.facts["model"]
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 84, in __getitem__
    raise jnpr.junos.exception.FactLoopError(
jnpr.junos.exception.FactLoopError: A loop was detected while gathering the model fact. The jnpr.junos.facts.personality module has already been called. Please report this error.

======================================================================
ERROR: test_ifd_style_classic (tests.unit.facts.test_ifd_style.TestIfdStyle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_ifd_style.py", line 35, in test_ifd_style_classic
    self.assertEqual(self.dev.facts["ifd_style"], "CLASSIC")
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 95, in __getitem__
    new_facts = self._callbacks[key](self._device)
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/facts/ifd_style.py", line 18, in get_facts
    if device.facts["personality"] == "SWITCH":
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 95, in __getitem__
    new_facts = self._callbacks[key](self._device)
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/facts/personality.py", line 24, in get_facts
    model = device.facts["model"]
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 84, in __getitem__
    raise jnpr.junos.exception.FactLoopError(
jnpr.junos.exception.FactLoopError: A loop was detected while gathering the model fact. The jnpr.junos.facts.personality module has already been called. Please report this error.

======================================================================
ERROR: test_ifd_style_switch (tests.unit.facts.test_ifd_style.TestIfdStyle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_ifd_style.py", line 30, in test_ifd_style_switch
    self.assertEqual(self.dev.facts["ifd_style"], "SWITCH")
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 95, in __getitem__
    new_facts = self._callbacks[key](self._device)
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/facts/ifd_style.py", line 18, in get_facts
    if device.facts["personality"] == "SWITCH":
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 95, in __getitem__
    new_facts = self._callbacks[key](self._device)
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/facts/personality.py", line 24, in get_facts
    model = device.facts["model"]
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 84, in __getitem__
    raise jnpr.junos.exception.FactLoopError(
jnpr.junos.exception.FactLoopError: A loop was detected while gathering the model fact. The jnpr.junos.facts.personality module has already been called. Please report this error.

======================================================================
ERROR: test_device_facts (tests.unit.test_device.TestDevice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/test_device.py", line 523, in test_device_facts
    assert self.dev.facts["version"] == facts["version"]
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/junos_eznc-2.6.7+27.gba799a81-py3.10.egg/jnpr/junos/factcache.py", line 119, in __getitem__
    raise RuntimeError(
RuntimeError: The jnpr.junos.facts.get_software_information module returned the model fact, but does not list model as a provided fact. Please report this error.

======================================================================
FAIL: test_domain_fact_from_config (tests.unit.facts.test_domain.TestDomain)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/pyez_release_py310_latest/venv/lib/python3.10/site-packages/mock/mock.py", line 1452, in patched
    return func(*newargs, **newkeywargs)
  File "/root/pyez_release_py310_latest/py-junos-eznc/tests/unit/facts/test_domain.py", line 30, in test_domain_fact_from_config
    self.assertEqual(self.dev.facts["domain"], "juniper.net")
AssertionError: None != 'juniper.net'

----------------------------------------------------------------------
```

**Comment by dineshbaburam91** [comment]
PyEZ support python3.10 and above
