### ISSUE TITLE
'Console' object has no attribute '_use_filter'

### ISSUE THREAD

**Issue by michaelcerne** [Juniper/py-junos-eznc#1314]
The `Console` object does not have the `_use_filter` attribute that the regular `Device` class provides.

The `Table` class expects this to be available. An error is thrown initializing a `Table` using a `Console`.

Reproduce with:

```python
from jnpr.junos import Device
from jnpr.junos.op.ethport import EthPortTable

with Device(host="xxx", port=21, user="xxx", passwd="xxx", mode="telnet") as dev:
    EthPortTable(dev).get()
```

Yields:

```
Traceback (most recent call last):
  File "<test_file>", line 5, in <module>
    EthPortTable(dev).get()
    ^^^^^^^^^^^^^^^^^
  File "<package_install_dir>\jnpr\junos\factory\table.py", line 37, in __init__
    self._use_filter = self._use_filter and self._dev._use_filter
                                            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Console' object has no attribute '_use_filter'
```

**Comment by michaelcerne** [comment]
Additionally, manually setting the `_use_filter` attribute on the allows us to proceed, but the test code then fails with:

```
File "<package_install_dir>\jnpr\junos\console.py", line 276, in _rpc_reply
    rpc_rsp_e = NCElement(
File "<package_install_dir>\ncclient\xml_.py", line 177, in __init__
    self.__doc = self.__transform_reply(result._root)
                                        ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute '_root'
```

This issue is mitigated by modifying `tty_netconf``'s `rpc` method to `return reply` rather than `return rsp`. `rsp` is a string, and of course, does not possess a `_root` attribute.

**Comment by michaelcerne** [comment]
The following code manually sets the missing `Console` attribute and monkey patches the `rpc` method to return as needed. When executed, the expected output (identical to using the `Device` class over SSH) is returned.

```python
from jnpr.junos import Device
from jnpr.junos.op.ethport import EthPortTable

# Fixes the rpc reply _root error.
old_rpc_pre_patch = tty_netconf.rpc
def rpc(self, cmd):
    original_response = old_rpc_pre_patch(self, cmd)
    updated_response = RPCReply(original_response, huge_tree=self._tty._huge_tree)
    updated_response.parse()
    return updated_response
tty_netconf.rpc = rpc

with Device(host="xxx", port=21, user="xxx", passwd="xxx", mode="telnet") as dev:

    # Fixes the _use_filter missing issue.
        if not hasattr(dev, "_use_filter"):
            dev._use_filter = False

    EthPortTable(dev).get() # Returns as expected.
```

If similar changes were introduced upstream, both issues would be corrected.

**Comment by chidanandpujar** [comment]
Fixed via https://github.com/Juniper/py-junos-eznc/pull/1335, hence closing this issue.
