### ISSUE TITLE
LLDP not working on ELS switches.

### ISSUE THREAD

**Issue by srossen** [Juniper/py-junos-eznc#310]
LLDP does not work when ran against ELS switches, you get:

```
TASK: [Get Pre-Change LLDP Information] *************************************** 
failed: [hostname-ex4300] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/username/.ansible/tmp/ansible-tmp-1415369107.39-120009485981090/junos_lldp", line 1608, in <module>
    main()
  File "/home/username/.ansible/tmp/ansible-tmp-1415369107.39-120009485981090/junos_lldp", line 78, in main
    module.fail_json(msg=err)
  File "/home/username/.ansible/tmp/ansible-tmp-1415369107.39-120009485981090/junos_lldp", line 1291, in fail_json
    print self.jsonify(kwargs)
  File "/home/username/.ansible/tmp/ansible-tmp-1415369107.39-120009485981090/junos_lldp", line 1260, in jsonify
    return json.dumps(data)
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ValueError("Unknown field: 'name'",) is not JSON serializable


FATAL: all hosts have already failed -- aborting
```

This appears be a result of non-ELS returning:
    `<lldp-local-interface>ge-0/1/1.0</lldp-local-interface>`
and ELS returning:
    `<lldp-local-port-id>xe-0/2/0</lldp-local-port-id>`

It may also be related non-ELS:
`<lldp-remote-port-description>PC Port</lldp-remote-port-description>`
and ELS
`<lldp-remote-port-id-subtype>Locally assigned</lldp-remote-port-id-subtype>`
`<lldp-remote-port-id>505</lldp-remote-port-id>`

hat tip to @supertylerc for the help on this.

**Comment by srossen** [comment]
This is now working current build.
