### ISSUE TITLE
Enforce facts/chassis.py to support new hardware

### ISSUE THREAD

**Issue by titom73** [Juniper/py-junos-eznc#329]
Hello,

In some cases, serial-number is not reported to chassis/serial-number neither in midplane. So when we get facts from device, exception is raised:

```
>>> from jnpr.junos import Device
>>> dev = Device(host='73.1.2.9', user='svc-netconf', password='nomios101')
>>> dev.open()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tgrimonet\AppData\Roaming\Python\Python27\site-packages\jnpr\junos\device.py", line 439, in open
    self.facts_refresh()
  File "C:\Users\tgrimonet\AppData\Roaming\Python\Python27\site-packages\jnpr\junos\device.py", line 660, in facts_refresh
    gather(self, self._facts)
  File "C:\Users\tgrimonet\AppData\Roaming\Python\Python27\site-packages\jnpr\junos\facts\chassis.py", line 56, in facts_chassis
    'chassis-module[name="Backplane"]/serial-number')[0].text
IndexError: list index out of range
```
Here is complete ```show chassis hardware | display xml``` from impacted device and then from Firefly SRX

```
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/14.1R1/junos">
    <chassis-inventory xmlns="http://xml.juniper.net/junos/14.1R1/junos-chassis">
        <chassis junos:style="inventory">
            <name>Chassis</name>
            <description>VMX</description>
            [...]
            <chassis-module>
                <name>FPC 0</name>
                <description>10x1G FPC</description>
                <chassis-sub-module>
                    <name>CPU</name>
                    <version>Rev. 1.0</version>
                    <part-number>RIOT</part-number>
                    <serial-number>123XYZ987</serial-number>
                </chassis-sub-module>
        [...]
        </chassis>
    </chassis-inventory>
    <cli>
        <banner></banner>
    </cli>
</rpc-reply>
```
SRX hardware:
```
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/12.1X47/junos">
    <chassis-inventory xmlns="http://xml.juniper.net/junos/12.1X47/junos-chassis">
        <chassis junos:style="inventory">
            <name>Chassis</name>
            <serial-number>6cf0dcb880e9</serial-number>
            <description>FIREFLY-PERIMETER</description>
            [...]
        </chassis>
    </chassis-inventory>
    <cli>
        <banner></banner>
    </cli>
</rpc-reply>
```

One solution might be to return value based on speciffic xPath per model in jnpr.junos.facts.chassis.py like example below:

```
    try:
        # vMX workarounf since XML path is different than others devices
        if(facts['model']=='VMX'): 
            facts['serialnumber'] = x_ch.find('chassis-module/chassis-sub-module/serial-number').text
        else:
            facts['serialnumber'] = x_ch.find('serial-number').text
    except:
        # if the toplevel chassis does not have a serial-number, then
        # check the Backplane chassis-module
        facts['serialnumber'] = x_ch.xpath(
            'chassis-module[name="Backplane"]/serial-number')[0].text
```
Best Regards

TiTom73

**Comment by vnitinv** [comment]
@shermdog  This was an issue with older VMs where if VM was not orchestrated in VMM environment, in that case serialid was not getting passed to the VM. This has been fixed in all newer VMs. We can for now change the status to close or under review.

**Comment by andydavidson** [comment]
How are you defining 'old VM' ?  I'm seeing same behaviour and error message that @titom73 reports in junos 14 devel vmx environment on kvm/linux.

**Comment by vnitinv** [comment]
@andydavidson  by old VM I meant Phase 1 VMs
