### ISSUE TITLE
facts_domain bug with missing /etc/resolv.conf

### ISSUE THREAD

**Issue by shermdog** [Juniper/py-junos-eznc#332]
There have been a few issues come up in Google Groups similar to:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 439, in open
    self.facts_refresh()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 660, in facts_refresh
    gather(self, self._facts)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/facts/domain.py", line 13, in facts_domain
    words = fs.cat('/etc/resolv.conf').split()
AttributeError: 'NoneType' object has no attribute 'split'
```

https://groups.google.com/forum/#!topic/junos-python-ez/aBl230sWXqQ
https://groups.google.com/forum/#!topic/junos-python-ez/WLa-5gWVdz8

Need to look into a better way of handling this (particularly VCF and logical systems).

**Comment by vnitinv** [comment]
Fixed under #340
