### ISSUE TITLE
Catch 'Not connected to NETCONF server' exception

### ISSUE THREAD

**Issue by shermdog** [Juniper/py-junos-eznc#339]
When trying to execute a RPC against a non-open Device the following exception is thrown (and not caught).  

Add exception to PyEZ to catch and report this (preferably without exiting).

```
>>> res = dev.rpc.get_config()
jnpr\junos\device.py:529: RuntimeWarning: An unknown exception occured - please report.
  warnings.warn("An unknown exception occured - please report.", RuntimeWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jnpr\junos\rpcmeta.py", line 43, in get_config
    return self._junos.execute(rpc)
  File "jnpr\junos\decorators.py", line 25, in wrapper
    return function(*args, **kwargs)
  File "jnpr\junos\device.py", line 516, in execute
    rpc_rsp_e = self._conn.rpc(rpc_cmd_e)._NCElement__doc
  File "C:\Python26\lib\site-packages\ncclient\manager.py", line 166, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "C:\Python26\lib\site-packages\ncclient\manager.py", line 226, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "C:\Python26\lib\site-packages\ncclient\operations\third_party\juniper\rpc.py", line 42, in request
    return self._request(rpc)
  File "C:\Python26\lib\site-packages\ncclient\operations\rpc.py", line 291, in _request
    self._session.send(req)
  File "C:\Python26\lib\site-packages\ncclient\transport\session.py", line 147, in send
    raise TransportError('Not connected to NETCONF server')
ncclient.transport.errors.TransportError: Not connected to NETCONF server
```

**Comment by shermdog** [comment]
Trying to execute RPC's against Devices that have never been opened also fails:

```python
>>> dev.rpc.get_config()
jnpr\junos\device.py:531: RuntimeWarning: An unknown exception occured - please report.
  warnings.warn("An unknown exception occured - please report.", RuntimeWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jnpr\junos\rpcmeta.py", line 43, in get_config
    return self._junos.execute(rpc)
  File "jnpr\junos\decorators.py", line 25, in wrapper
    return function(*args, **kwargs)
  File "jnpr\junos\device.py", line 516, in execute
    rpc_rsp_e = self._conn.rpc(rpc_cmd_e)._NCElement__doc
AttributeError: 'NoneType' object has no attribute 'rpc'
```
