### ISSUE TITLE
view.py KeyError:'mac_stats'

### ISSUE THREAD

**Issue by ramelito** [Juniper/py-junos-eznc#352]
smth wrong with view.py
```python
>>> from jnpr.junos.op.ethport import *
>>> eths = EthPortTable(dev)
>>> eths.get()
>>> ae0=eths['ae0']
>>> ae0.keys()
['oper', 'rx_packets', 'macaddr', 'rx_bytes', 'admin', 'mtu', 'running', 'link_mode', 'tx_bytes', 'tx_packets', 'present']
>>> ae0.items()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/jnpr/junos/factory/view.py", line 120, in items
    return zip(self.keys(), self.values())
  File "/usr/lib64/python2.7/site-packages/jnpr/junos/factory/view.py", line 116, in values
    return [getattr(self, field) for field in self.keys()]
  File "/usr/lib64/python2.7/site-packages/jnpr/junos/factory/view.py", line 223, in __getattr__
    found = self._groups[item['group']].xpath(item['xpath'])
KeyError: 'mac_stats'
```

**Comment by shermdog** [comment]
Hi @ramelito,

Please open a thread in our Google Group to discuss.

https://groups.google.com/forum/#!forum/junos-python-ez

Also please include the content of 
```
eths.savexml(path='eths.xml')
```

Thanks,
-Rick

**Comment by shermdog** [comment]
Closing from lack of response.
