### ISSUE TITLE
Unable to connect to MX3300

### ISSUE THREAD

**Issue by zetasyanthis** [Juniper/py-junos-eznc#376]
Looks like there's an issue with hostnames when connecting to the MX3300.  Hostname is set to 'testswitch'.

Code block:

	from lxml import etree
	from jnpr.junos import Device

	class Switch(object):
	    pass

	class JunosSwitch(Switch):

	    USER = 'root'
	    PASSWORD = 'admin123'

	    def __init__(self, host):
		self._device = Device(
		    user=self.USER,
		    password=self.PASSWORD,
		    host=host)
		self._device.open()

	    def __del__(self):
		self._device.close()

	    @property
	    def mac_address_table(self):
		return self._device.rpc.get_ethernet_switching_table_information()

	def test():
	    j = JunosSwitch('10.0.150.1')
	    print etree.tostring(j.mac_address_table)

	if __name__ == '__main__':
	    test()

Error:

    [root@lab-swe ~]# python switch.py 
    Traceback (most recent call last):
      File "switch.py", line 34, in <module>
        test()
      File "switch.py", line 30, in test
        j = JunosSwitch('10.0.150.1')
      File "switch.py", line 19, in __init__
        self._device.open()
      File "/usr/lib/python2.6/site-packages/jnpr/junos/device.py", line 457, in open
        self.facts_refresh()
      File "/usr/lib/python2.6/site-packages/jnpr/junos/device.py", line 715, in facts_refresh
        gather(self, self._facts)
      File "/usr/lib/python2.6/site-packages/jnpr/junos/facts/swver.py", line 130, in facts_software_version
        facts['hostname'] = x_swver.findtext(xpath)
      File "lxml.etree.pyx", line 1288, in lxml.etree._Element.findtext (src/lxml/lxml.etree.c:36579)
      File "/usr/lib64/python2.6/site-packages/lxml/_elementpath.py", line 231, in findtext
        el = find(elem, path)
      File "/usr/lib64/python2.6/site-packages/lxml/_elementpath.py", line 210, in find
        it = iterfind(elem, path)
      File "/usr/lib64/python2.6/site-packages/lxml/_elementpath.py", line 200, in iterfind
        selector = _build_path_iterator(path)
      File "/usr/lib64/python2.6/site-packages/lxml/_elementpath.py", line 184, in _build_path_iterator
        selector.append(ops[token[0]](_next, token))
      File "/usr/lib64/python2.6/site-packages/lxml/_elementpath.py", line 140, in prepare_predicate
        raise SyntaxError("invalid node predicate")
    SyntaxError: invalid node predicate
    Exception ncclient.transport.errors.SessionCloseError: SessionCloseError('Unexpected session close\nIN_BUFFER: `\n`',) in <bound method JunosSwitch.__del__ of <__main__.JunosSwitch object at 0x22e0f50>> ignored

**Comment by shermdog** [comment]
Hi @zetasyanthis 

You can work around this issue with:
```python
self._device.open(gather_facts=False)
```

Please post the version of Junos this device is running.

If you could test with the latest development version that will also help me identify if this issue has already been cleared up or not.

```
pip install git+https://github.com/Juniper/py-junos-eznc.git
```

Thanks,
-Rick

**Comment by zetasyanthis** [comment]
Thanks for the quick response, @shermdog.

I just found out that something must have gone wrong in the install.  Looks like the version of python-lxml was old and somehow went undetected on my system...  Not sure how.  An update of that library fixed the issue.  Apologies!
