### ISSUE TITLE
PyEZ Device(...) API with remote host not working with JUNOS OCCAM builds

### ISSUE THREAD

**Issue by dssatya** [Juniper/py-junos-eznc#420]
$% more sample.py
#!/usr/bin/python
import sys
from pprint import pprint
from jnpr.junos import Device

def main():
       dev = Device(host='x.x.x.x', user='xxxx', password='xxxx')
       dev.open()
       print(dev)

if __name__ == '__main__':
    main()
$%

$% python sample.py
Traceback (most recent call last):
  File "sample.py", line 14, in <module>
    main()
  File "sample.py", line 10, in main
    dev.open()
  File "../../../../../../../src/dist/python-add-ons/junos-eznc/lib/jnpr/junos/device.py", line 457, in open
  File "../../../../../../../src/dist/python-add-ons/junos-eznc/lib/jnpr/junos/device.py", line 715, in facts_refresh
  File "../../../../../../../src/dist/python-add-ons/junos-eznc/lib/jnpr/junos/facts/swver.py", line 148, in facts_software_version
IndexError: list index out of range
$%

**Comment by vnitinv** [comment]
Hi @dssatya 
On latest code base, We don't see this issue. Whats the version of PyEZ you are using?
>>> from jnpr.junos import version
>>> version.VERSION
'1.2.2'

**Comment by vnitinv** [comment]
@dssatya Closing for now as I dont find any issue using latest PyEZ on occam
