### ISSUE TITLE
dev.open() results in traceback for devices running Junos 15.1F track

### ISSUE THREAD

**Issue by schornig** [Juniper/py-junos-eznc#440]
Traceback (most recent call last):
  File "/Users/eschornig/Desktop/scripts/LLDP_Sniffer/LldpSniffer.py", line 30, in <module>
    dev.open()
  File "/Library/Python/2.7/site-packages/jnpr/junos/device.py", line 495, in open
    self.facts_refresh()
  File "/Library/Python/2.7/site-packages/jnpr/junos/device.py", line 773, in facts_refresh
    gather(self, self._facts)
  File "/Library/Python/2.7/site-packages/jnpr/junos/facts/swver.py", line 195, in facts_software_version
    facts['version_info'] = version_info(facts['version'])
  File "/Library/Python/2.7/site-packages/jnpr/junos/facts/swver.py", line 11, in __init__
    self.major = tuple(map(int, m1.group(1).split('.')))  # creates tuyple
ValueError: invalid literal for int() with base 10: '1F'
[Finished in 4.3s with exit code 1]

===========================================================

After adding "F" in regexp @ swver.py line 8:
        m1 = re.match('(.*?)([RFBIXS-])(.*)', verstr)

------>>>>
duma
version_RE1 : 15.1F-20151004.0
version_RE0 : 15.1F-20151004.0
version_info : junos.version_info(major=(15, 1), type=F, minor=-20151004, build=0)
version : 15.1F-20151004.0

**Comment by vnitinv** [comment]
Hi @schornig This looks like some special junos build (private/dev). As we follow different naming convention for such builds, its always tough to support all of them. Said that, we always try to make sure its supported for any build name which that goes to customer for sure and also if we can support these special names. You can send a pull request with the above changes so that we can test it properly and merge after discussion.
