### ISSUE TITLE
Strange exception when call .close()

### ISSUE THREAD

**Issue by pavel-odintsov** [Juniper/py-junos-eznc#466]
Hello, folks!

I'm using eznc with SRX240:
```bash
from pprint import pprint
from jnpr.junos import Device

dev = Device(host='10.0.x.x', user='view_config', password='xxxxx' )
dev.open()

pprint( dev.facts )

#dev.close()
```

It works pretty nice with commented out "dev.close":
```bash
{'2RE': False,
 'HOME': '/cf/var/home/view_config',
 'RE0': {'last_reboot_reason': '0x1:power cycle/failure',
         'model': 'RE-SRX240H',
         'status': 'OK',
         'up_time': '4 days, 13 hours, 7 minutes, 50 seconds'},
 'domain': None,
 'fqdn': 'selectel-router',
 'hostname': 'selectel-router',
 'ifd_style': 'CLASSIC',
 'model': 'SRX240H',
 'personality': 'SRX_BRANCH',
 'serialnumber': 'AG3211AA0462',
 'srx_cluster': False,
 'switch_style': 'VLAN',
 'vc_capable': False,
 'version': '12.1X46-D35.1',
 'version_info': junos.version_info(major=(12, 1), type=X, minor=(46, 'D', 35), build=1)}
```

But when I uncomment dev.close():
```python
from pprint import pprint
from jnpr.junos import Device

dev = Device(host='10.0.6.1', user='view_config', password='DJb2x92VDIpa99ct' )
dev.open()

pprint( dev.facts )
dev.close()
```

I still get device information but also get exception about permission denied:
```bash
python junos_ez.py 
{'2RE': False,
 'HOME': '/cf/var/home/view_config',
 'RE0': {'last_reboot_reason': '0x1:power cycle/failure',
         'model': 'RE-SRX240H',
         'status': 'OK',
         'up_time': '4 days, 13 hours, 10 minutes, 45 seconds'},
 'domain': None,
 'fqdn': 'selectel-router',
 'hostname': 'selectel-router',
 'ifd_style': 'CLASSIC',
 'model': 'SRX240H',
 'personality': 'SRX_BRANCH',
 'serialnumber': 'AG3211AA0462',
 'srx_cluster': False,
 'switch_style': 'VLAN',
 'vc_capable': False,
 'version': '12.1X46-D35.1',
 'version_info': junos.version_info(major=(12, 1), type=X, minor=(46, 'D', 35), build=1)}
Traceback (most recent call last):
  File "junos_ez.py", line 9, in <module>
    dev.close()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 504, in close
    self._conn.close_session()
  File "/usr/local/lib/python2.7/dist-packages/ncclient/manager.py", line 157, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/ncclient/manager.py", line 227, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/ncclient/operations/session.py", line 28, in request
    return self._request(new_ele("close-session"))
  File "/usr/local/lib/python2.7/dist-packages/ncclient/operations/rpc.py", line 338, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: permission denied

```

**Comment by pavel-odintsov** [comment]
Is it OK? Something going wrong definitely... What sort of additional permissions required to close netconf connection?

**Comment by pavel-odintsov** [comment]
Fixed with: 
```bash
set system login user view_config class read-only
commit
```

**Comment by shabbir1282** [comment]
Thank you very much, it helped me solve this issue. this must be documented somewhere.

**Comment by Povezi** [comment]
+1 I had the same problem

**Comment by leandrofmilani** [comment]
Does anyone know which specific command or permission is necessary to add to a class that will allow closing the connection?

**Comment by tonusoo** [comment]
> Does anyone know which specific command or permission is necessary to add to a class that will allow closing the connection?

`.*close-session` under [allow-commands](https://www.juniper.net/documentation/en_US/junos/topics/reference/configuration-statement/allow-commands-edit-system.html)
