### ISSUE TITLE
jnpr.junos.utils.config Load command error - SRX650 & SRX240 cluster

### ISSUE THREAD

**Issue by jbahou** [Juniper/py-junos-eznc#477]
650 = 12.1X46-D35.1
240 = 12.1X46-D35.1

```
#!/usr/bin/python

from jnpr.junos import Device
from jnpr.junos.utils.config import Config
from getpass import getpass

#Set user password for device connection
mypwd = getpass()

#Specify device parameters
dev = Device('device',port=830,user='username',password=mypwd)

#Connect to specified device
dev.open()

#Setting Configuration parameter
cu = Config(dev)
print cu

#Candidate configuration
setCmd = 'set system login message "Welcome Admin!  You are among the mighty"'

#Load candidate configuration
cu.load(setCmd, format="set")
cu.pdiff()

#print candidate configuration
print cu.pdiff()
```

Outputs:

Password:

```
jnpr.junos.utils.Config(device)
C:\Python27\lib\site-packages\junos_eznc-1.0.0-py2.7.egg\jnpr\junos\utils\config.py:273: FutureWarning: The behavior
of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if any([e.find('[error-severity="error"]') for e in rerrs]):
Traceback (most recent call last):
  File "SRX_Conn.py", line 24, in <module>
    cu.load(setCmd, format="set")
  File "C:\Python27\lib\site-packages\junos_eznc-1.0.0-py2.7.egg\jnpr\junos\utils\config.py", line 296, in load
    return try_load(rpc_contents, rpc_xattrs)
  File "C:\Python27\lib\site-packages\junos_eznc-1.0.0-py2.7.egg\jnpr\junos\utils\config.py", line 274, in try_load
    raise err
jnpr.junos.exception.RpcError
```

**Comment by vnitinv** [comment]
@jbahou I can notice you are using very old PyEZ (1.0.0). Do upgrade to 1.3.1 and give a try.
Closing this issue for now. Please do re-open if the issue still exists.
