### ISSUE TITLE
reboot function in jnpr.junos.utils.sw raises an exception. 

### ISSUE THREAD

**Issue by rajvidhimar** [Juniper/py-junos-eznc#481]
I am trying to reboot a vmx using pyEZ:
```
dev = Device(host='xxxxx', user='xxxxx', password='xxxxx', gather_facts=True)
dev.open()
sw = SW(dev)
ok = sw.reboot()
dev.close()
```
This gives the following error:
```
Traceback (most recent call last):
  File "Documents/facts.py", line 15, in <module>
    ok = sw.reboot()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/sw.py", line 526, in reboot
    raise err
jnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: None, message: error: 
error: System shutdown time has arrived)
```

**Comment by vnitinv** [comment]
@rajvidhimar Issue was tracked to be on device side. Hence PR has been raised accordingly. Thanks
