### ISSUE TITLE
inexistent field in the RPC output causes exception when assembling the operational table

### ISSUE THREAD

**Issue by dmontagner** [Juniper/py-junos-eznc#601]
If one of the fields does not exist (i.e., user has not configured it on the router), it will cause an exception like this:

```
BGP peer description: ABC
BGP peer state: Established
BGP peer address: x.y.z.w
BGP peer ASN: 65100
Traceback (most recent call last):
  File "./bb3.using.pyez.tables.py", line 137, in <module>
    main()
  File "./bb3.using.pyez.tables.py", line 132, in main
    print("BGP peer description: " + bgpPeer.peerDescription)
TypeError: cannot concatenate 'str' and 'NoneType' objects
2016-09-18 20:05:28,650	DEBUG -- MainProcess transport.py:1563 -- EOF in transport thread
2016-09-18 20:05:28,651	DEBUG -- MainProcess ssh.py:553 -- Broke out of main loop, error=SessionCloseError('Unexpected session close\nIN_BUFFER: `\n`',)
2016-09-18 20:05:28,651	DEBUG -- MainProcess session.py:74 -- dispatching error to <ncclient.operations.rpc.RPCReplyListener object at 0x109863210>
```

The exception above is cause because the next BGP peer analysed by the table does not have the neighbour description configured.

- example of BGP session without description:

```
dmontagner@pe1# show protocols bgp
group ROUTE_REFLECTORS {
    type internal;
    local-address a1.b1.c1.d1;
    family inet-vpn {
        unicast;
    }
    family l2vpn {
        signaling;
    }
    export [ POL1 POL2 ];
    vpn-apply-export;
    neighbor x.y.z.w1;
    neighbor x.y.z.w2;
}
```

- the problem doesn't occur if I configure the session above as follows:

```
dmontagner@pe1# show protocols bgp
group ROUTE_REFLECTORS {
    type internal;
    local-address a1.b1.c1.d1;
    family inet-vpn {
        unicast;
    }
    family l2vpn {
        signaling;
    }
    export [ POL1 POL2 ];
    vpn-apply-export;
    neighbor x.y.z.w1 {
        description RR1;
    }
    neighbor x.y.z.w2 {
        description RR2;
    }
}
```

- This is the definition of the Operational Table

```
    yaml_data = """
---
BgpSummaryTable:
    rpc: get-bgp-summary-information
    item: bgp-peer
    key: peer-address
    view: BgpSummaryTableView

BgpSummaryTableView:
    fields:
        peerAddress: peer-address
        peerAS: peer-as
        peerDescription: description
        peerState: peer-state
"""
```

**Comment by stacywsmith** [comment]
@dmontagner 

It looks like this traceback came from your code rather than from PyEZ.
```
Traceback (most recent call last):
  File "./bb3.using.pyez.tables.py", line 137, in <module>
    main()
  File "./bb3.using.pyez.tables.py", line 132, in main
    print("BGP peer description: " + bgpPeer.peerDescription)
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

It looks like your code had the line:
```
    print("BGP peer description: " + bgpPeer.peerDescription)
``1
and that `bgpPeer.peerDescription` had the value `None`. That seems like a reasonable value for the Operational Table to return if a description is not configured.

**Comment by dmontagner** [comment]
Hi Stacy,

you are right.

I fixed the problem with this:

    for bgpPeer in bgpSummary:
        print("BGP peer address: " + str(bgpPeer.peerAddress))
        print("BGP peer ASN: " + str(bgpPeer.peerAS))
        print("BGP peer description: " + str(bgpPeer.peerDescription))
        print("BGP peer state: " + str(bgpPeer.peerState))
        print("---")

I have added str() function into the above code and now it does not raise an exception if it receives None.

Thanks

**Comment by dmontagner** [comment]
The issue is on my code and not on pyEZ.
