### ISSUE TITLE
Authentication fails when using ECDSA key (RSA key works fine)

### ISSUE THREAD

**Issue by privateip** [Juniper/py-junos-eznc#605]
When using an ECDSA key, `open()` causes a `ConnectAuthError`; however, this works fine with RSA keys.

Attempting to connect with ECDSA key

```
>>> from jnpr.junos import Device
>>> dev = Device('vsrx01', user='test', ssh_private_key_file='./test')
>>> dev.open()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sprygada/.virtualenvs/ansible/lib/python2.7/site-packages/jnpr/junos/device.py", line 880, in open
    raise EzErrors.ConnectAuthError(self)
jnpr.junos.exception.ConnectAuthError: ConnectAuthError(vsrx01)
```

SSH and key work fine

```
$ ssh -i ./test test@vsrx01
--- JUNOS 15.1X49-D15.4 built 2015-07-31 02:20:21 UTC
test@vsrx01>
```

Attempting to connect with RSA key

```
>>> dev = Device('vsrx01', user='ansible', ssh_private_key_file='ansible')
>>> dev.open()
Device(vsrx01)
>>> dev.facts
{'domain': 'ansible.com', 'hostname': 'vsrx01', 'ifd_style': 'CLASSIC', 'version_info': junos.version_info(major=(15, 1), type=X, minor=(49, 'D', 15), build=4), '2RE': False, 'serialnumber': 'adc382ed18b0', 'fqdn': 'vsrx01.ansible.com', 'switch_style': 'NONE', 'version': '15.1X49-D15.4', 'HOME': '/var/home/ansible', 'srx_cluster': False, 'model': 'VSRX', 'RE0': {'status': 'Testing', 'last_reboot_reason': 'Router rebooted after a normal shutdown.', 'model': 'VSRX RE', 'up_time': '37 days, 1 hour, 37 minutes, 53 seconds'}, 'vc_capable': False, 'personality': 'UNKNOWN'}
```

Version information

```
>>> from jnpr.junos.version import VERSION
>>> VERSION
'2.0.1'
>>>
>>>
>>> import ncclient
>>> ncclient.__version__
(0, 5, 2)
```

**Comment by stacywsmith** [comment]
@privateip ncclient doesn't currently support ECDSA keys. I've submitted: https://github.com/ncclient/ncclient/pull/158

**Comment by stacywsmith** [comment]
Tracking via https://github.com/ncclient/ncclient/pull/158

**Comment by rrashmi1** [comment]
I had also  experienced this issue while running ansible playbook inside Docker in windows. when I tried the code in the same in the python terminal. 
You can try updating ncclient and make sure your RSA keys are having same test as you've saved in the device. Keeping it same solved me to this issue. 

Now i'm able to login to the device. 

happy coding.!!!
