### ISSUE TITLE
Version 2.0.1 does not give full XML error messages 

### ISSUE THREAD

**Issue by yunli2004** [Juniper/py-junos-eznc#624]
``` xml
Difference in Error message description. 1.0.2 has a very accurate thorough description while 2.0.1 does not give me enough info.
 
Committing following a.conf
[root@space-000c2989d979 site-packages] cat a.conf
 
interfaces {
    xe-0/0/0 {
        delete:
        unit 0;
 
        flexible-vlan-tagging;
        encapsulation extended-vlan-bridge;
 
        unit 11 {
            vlan-id 11;
       }
   }
}
 
With 1.0.2, I got following error in yellow: This is really descriptive for both customer and for our internal debugging. So we want this behavior.
 
[root@space-000c2989d979 site-packages]# /opt/python2.7/bin/python2.7 c.py 192.168.2.124 a.conf
192.168.2.124 connected
192.168.2.124 updateConfig started
192.168.2.124 Locked config
192.168.2.124 Rollbacked any other config
192.168.2.124 Load config as candidate
updateDeviceConfiguration failed for 192.168.2.124, CommitError: <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/14.1X53/junos" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:b389ef44-e73d-490d-8461-1102c8f0625e">
<commit-results>
<rpc-error>
<error-type>application</error-type>
<error-tag>invalid-value</error-tag>
<error-severity>error</error-severity>
<error-path>[edit interfaces xe-0/0/0 unit 0 family ethernet-switching interface-mode]</error-path>
<error-message>mgd: interface-mode access is allowed only for untagged interfaces</error-message>
<error-info>
<bad-element>interface-mode access</bad-element>
</error-info>
</rpc-error>
<rpc-error>
<error-severity>warning</error-severity>
<error-path>[edit protocols]</error-path>
<error-message>mgd: requires 'bgp' license</error-message>
<error-info>
<bad-element>bgp</bad-element>
</error-info>
</rpc-error>
<rpc-error>
<error-type>protocol</error-type>
<error-tag>operation-failed</error-tag>
<error-severity>error</error-severity>
<error-message>
commit failed: (statements constraint check failed)
</error-message>
</rpc-error>
</commit-results>
</rpc-reply>
, {'source': None, 'message': None, 'bad_element': None, 'severity': None, 'edit_path': None}
192.168.2.124 updateConfig ended
192.168.2.124 connection closed
 
 
With 2.0.1, I got very little error message. 2 sub issues are:
1.  I couldn’t find severity==error in the exception. I only got severity==warning.
2.  Where can I get the full xml descriptive error messages like with version 1.0.2?
 
[root@space-000c2989d979 site-packages]# /opt/python2.7/bin/python2.7 b.py 192.168.2.124 a.conf
192.168.2.124 connected
192.168.2.124 updateConfig started
192.168.2.124 Locked config
192.168.2.124 Rollbacked any other config
updateDeviceConfiguration failed for 192.168.2.124, ConfigLoadError: ConfigLoadError(severity: warning, bad_element: None, message: warning: statement not found), {'source': None, 'message': 'statement not found', 'bad_element': None, 'severity': 'warning', 'edit_path': None}
Found only warnings. Ignored
192.168.2.124 updateConfig ended
192.168.2.124 connection closed

**Comment by stacywsmith** [comment]
This issue is mistaken.

There was an actual issue in 1.0.2 where the `load()` method did not properly raise an exception even though there were `<rpc-error>` element in the XML reply. That has now been fixed and version 2.0.1 now correctly raises an exception when an `<rpc-error>` element is present in the XML.

In your particular case, the exception raised by the `load()` method is of severity warning and has the message `statement not found`:
```
updateDeviceConfiguration failed for 192.168.2.124, ConfigLoadError: ConfigLoadError(severity: warning, bad_element: None, message: warning: statement not found), {'source': None, 'message': 'statement not found', 'bad_element': None, 'severity': 'warning', 'edit_path': None}
Found only warnings. Ignored
192.168.2.124 updateConfig ended
```

Your code has a bug which does not properly handle warnings produced by the `load()` method. Because both the `load()` and `commit()` methods are in the same `try/except` block the `commit()` never gets executed when a warning is raised by the `load()` method.

So, your code currently has:
```
...
    try:
        # make sure no changes are taken from CLI candidate config left over
        configurationUnit.rollback()
        print '%s Rollbacked any other config' % sys.argv[1]
        configurationUnit.load(config, format='text')
        print '%s Load config as candidate' % sys.argv[1]

        configurationUnit.commit()
        print '%s Committed config' % sys.argv[1]
    except CommitError as exc:
        print 'updateDeviceConfiguration failed for %s, CommitError: %s, %s' % (sys.argv[1], exc.__repr__(), exc.rpc_error)
        only_warnings = True
        for err in exc.errs:
            if err['severity'] == 'error':
                only_warnings = False
        if not only_warnings:
            configurationUnit.rollback()
            raise
        else:
            print 'Found only warnings. Ignored'
    except ConfigLoadError as exc:
        print 'updateDeviceConfiguration failed for %s, ConfigLoadError: %s, %s' % (sys.argv[1], exc.__repr__(), exc.rpc_error)
        only_warnings = True
        for err in exc.errs:
            if err['severity'] == 'error':
                only_warnings = False
        if not only_warnings:
            configurationUnit.rollback()
            raise
        else:
            print 'Found only warnings. Ignored'
...
```

When the `ConfigLoadError` exception is raised, the `except` block correctly identifies it as only a warning. You can see that from the `Found only warnings. Ignored` message in the above output. However, this means the `commit()` is never executed. In version 1.0.2, the `load()` method fails to raise the exception for the `statement not found` warning, the bug in your code is not triggered, and the `commit()` method is actually executed. It is then the `commit()` method which results in a `CommitError` exception being raised with the details of exactly what caused the commit to fail.

If I adjust the code in your script to this:
```
...
    try:
        # make sure no changes are taken from CLI candidate config left over
        configurationUnit.rollback()
        print '%s Rollbacked any other config' % sys.argv[1]
        try:
            configurationUnit.load(config, format='text')
        except ConfigLoadError as exc:
            only_warnings = True
            for err in exc.errs:
                if err['severity'] == 'error':
                    only_warnings = False
            if not only_warnings:
                print 'updateDeviceConfiguration failed for %s, ConfigLoadError: %s, %s' % (sys.argv[1], exc.__repr__(), exc.rpc_error)
                configurationUnit.rollback()
                raise
            else:
                print 'Found only warnings. Ignored'
        print '%s Load config as candidate' % sys.argv[1]
        configurationUnit.commit()
        print '%s Committed config' % sys.argv[1]
    except CommitError as exc:
        only_warnings = True
        for err in exc.errs:
            if err['severity'] == 'error':
                only_warnings = False
        if not only_warnings:
            print 'updateDeviceConfiguration failed for %s, CommitError: %s, %s' % (sys.argv[1], exc.__repr__(), exc.rpc_error)
            configurationUnit.rollback()
            raise
        else:
            print 'Found only warnings. Ignored'
...
```

You now see the warning from the `load()` method is correctly ignored and the `CommitError` exception is raised and contains all of the same details as in version 1.0.2.

```
[root@space-000c2989d979 pyez]# /opt/python2.7/bin/python2.7 ./b.new.py 192.168.2.224 a.conf
192.168.2.224 connected
192.168.2.224 updateConfig started
192.168.2.224 Locked config
192.168.2.224 Rollbacked any other config
Found only warnings. Ignored
192.168.2.224 Load config as candidate
updateDeviceConfiguration failed for 192.168.2.224, CommitError: CommitError(edit_path: [edit interfaces xe-0/0/0], bad_element: unit 11, message: warning: mgd: requires 'bgp' license
error: interface needs to be in a bridge-domain or evpn to support family bridge
error: configuration check-out failed), {'source': 'dcd', 'message': 'interface needs to be in a bridge-domain or evpn to support family bridge', 'bad_element': 'unit 11', 'severity': 'error', 'edit_path': '[edit interfaces xe-0/0/0]'}
192.168.2.224 updateConfig ended
192.168.2.224 unknown error, CommitError(edit_path: [edit interfaces xe-0/0/0], bad_element: unit 11, message: warning: mgd: requires 'bgp' license
error: interface needs to be in a bridge-domain or evpn to support family bridge
error: configuration check-out failed)
StackTrace: Traceback (most recent call last):
  File "./b.new.py", line 73, in <module>
    updateConfig(deviceConnection, config)
  File "./b.new.py", line 38, in updateConfig
    configurationUnit.commit()
  File "/opt/python2.7/lib/python2.7/site-packages/junos_eznc-2.0.1-py2.7.egg/jnpr/junos/utils/config.py", line 129, in commit
    raise CommitError(cmd=err.cmd, rsp=err.rsp, errs=err.errs)
CommitError: CommitError(edit_path: [edit interfaces xe-0/0/0], bad_element: unit 11, message: warning: mgd: requires 'bgp' license
error: interface needs to be in a bridge-domain or evpn to support family bridge
error: configuration check-out failed)

Traceback (most recent call last):
  File "./b.new.py", line 73, in <module>
    updateConfig(deviceConnection, config)
  File "./b.new.py", line 38, in updateConfig
    configurationUnit.commit()
  File "/opt/python2.7/lib/python2.7/site-packages/junos_eznc-2.0.1-py2.7.egg/jnpr/junos/utils/config.py", line 129, in commit
    raise CommitError(cmd=err.cmd, rsp=err.rsp, errs=err.errs)
jnpr.junos.exception.CommitError: CommitError(edit_path: [edit interfaces xe-0/0/0], bad_element: unit 11, message: warning: mgd: requires 'bgp' license
error: interface needs to be in a bridge-domain or evpn to support family bridge
error: configuration check-out failed)
[root@space-000c2989d979 pyez]# 
```

So, the bottom line is that your code had a bug that wasn't previously exposed because of a bug in PyEZ version 1.0.2. Now that the PyEZ bug has been fixed it exposed the bug in your code.
