### ISSUE TITLE
Old version 1.0.2 does not get version info from QFX5200

### ISSUE THREAD

**Issue by yunli2004** [Juniper/py-junos-eznc#625]
``` xml
I can’t get qfx5200 version info with 1.0.2.
 
[root@space-000c2989d979 site-packages]# /opt/python2.7/bin/python2.7 a.py 192.168.2.224
192.168.2.224 connected
192.168.2.224 unknown error, list index out of range
StackTrace: Traceback (most recent call last):
  File "a.py", line 15, in <module>
    deviceConnection.facts_refresh()
  File "/opt/python2.7/lib/python2.7/site-packages/junos_eznc-1.0.2-py2.7.egg/jnpr/junos/device.py", line 660, in facts_refresh
    gather(self, self._facts)
  File "/opt/python2.7/lib/python2.7/site-packages/junos_eznc-1.0.2-py2.7.egg/jnpr/junos/facts/swver.py", line 145, in facts_software_version
    )[0].text
IndexError: list index out of range
 
Traceback (most recent call last):
  File "a.py", line 15, in <module>
    deviceConnection.facts_refresh()
  File "/opt/python2.7/lib/python2.7/site-packages/junos_eznc-1.0.2-py2.7.egg/jnpr/junos/device.py", line 660, in facts_refresh
    gather(self, self._facts)
  File "/opt/python2.7/lib/python2.7/site-packages/junos_eznc-1.0.2-py2.7.egg/jnpr/junos/facts/swver.py", line 145, in facts_software_version
    )[0].text
IndexError: list index out of range
 
 
However, I can get qfx5200 version info with 2.0.1 without problem.
 
[root@space-000c2989d979 site-packages]# /opt/python2.7/bin/python2.7 a.py 192.168.2.224
192.168.2.224 connected
qfx5200-32c-32q
192.168.2.224 connection closed
 
Is there a workaround for me to get the qfx5200 model with 1.0.2?
FYI, I have no problem getting qfx5100 model with 1.0.2. Maybe qfx5200 model info has a new xml schema?
```

**Comment by stacywsmith** [comment]
The issue that you are experiencing is because the QFX5200 is running a Junos release >= 15.1. There were multiple enhancements made to PyEZ since version 1.0.2 to handle the changes that came in Junos >= 15.1. There are no plans to backport those changes to PyEZ version 1.0.2.
