### ISSUE TITLE
catch exceptions for close()

### ISSUE THREAD

**Issue by tylerjordan** [Juniper/py-junos-eznc#738]
If a connection is opened to a device successfully, but then there are connectivity issues that cause an issue when trying to close the session, there will be an uncaught exception in device.py (close method). I'd like to suggest putting **self._conn.close_session()** within a try and raise specific exceptions.

Here is the Trace...
```
Traceback (most recent call last):
  File "device_refresh.py", line 1777, in <module>
    check_loop(subsetlist)
  File "device_refresh.py", line 1610, in check_loop
    check_main(record, total_num, curr_num)
  File "device_refresh.py", line 1675, in check_main
    dev.close()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/junos_eznc-2.0.1-py2.7.egg/jnpr/junos/device.py", line 938, in close
    self._conn.close_session()
  File "build/bdist.linux-x86_64/egg/ncclient/manager.py", line 161, in wrapper
  File "build/bdist.linux-x86_64/egg/ncclient/manager.py", line 231, in execute
  File "build/bdist.linux-x86_64/egg/ncclient/operations/session.py", line 28, in request
  File "build/bdist.linux-x86_64/egg/ncclient/operations/rpc.py", line 343, in _request
ncclient.operations.errors.TimeoutExpiredError: ncclient timed out while waiting for an rpc reply.
```

**Comment by rahkumar651991** [comment]
seems to have been handled in code. 
closing the issue.
