### ISSUE TITLE
connected using localhost on-box, StartShell usage throws exception

### ISSUE THREAD

**Issue by vnitinv** [Juniper/py-junos-eznc#766]
When PyEZ running on-box and connected using localhost, StartShell usage throws exception
We should provide a proper error message and also document the same.

```python
> op StartShell.py                              
Traceback (most recent call last):
  File "/var/db/scripts/op/StartShell.py", line 6, in <module>
with StartShell(dev) as ss:
  File "../../../../../../../../src/dist/python-add-ons/junos-eznc/lib/jnpr/junos/utils/start_shell.py", line 127, in __enter__
  File "../../../../../../../../src/dist/python-add-ons/junos-eznc/lib/jnpr/junos/utils/start_shell.py", line 79, in open
  File "../../../../../../../../src/gpl-dist/python-add-ons/paramiko/paramiko/client.py", line 251, in connect
  File "../../../../../../../../src/gpl-dist/python-add-ons/paramiko/paramiko/util.py", line 270, in retry_on_signal
  File "../../../../../../../../src/gpl-dist/python-add-ons/paramiko/paramiko/client.py", line 251, in <lambda>
  File "../../../../../../../src/dist/python/Lib/socket.py", line 224, in meth
socket
.
error
: 
getsockaddrarg: bad family```

For tracking GNAT PR 1297416

**Comment by rahkumar651991** [comment]
Closing the issue as the internal PR seem to be resolved.
