### ISSUE TITLE
RuntimeWarning: An unknown exception occured - please report.

### ISSUE THREAD

**Issue by njayarama** [Juniper/py-junos-eznc#777]
unable to pull huge file of 'messages' from device with rpc.get_log. what is a better solution to search 'log messages' from device?

code snippet:
        dev = Device(host=ibx_fqdn, user=sw_user, passwd=sw_passwd).open()
        dev.timeout = 3000
        with open('local.log', 'w') as fp:
                fp.write(dev.rpc.get_log(filename='messages').text)     #to save in local copy
        dev.close()

/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py:794: RuntimeWarning: An unknown exception occured - please report.
  RuntimeWarning)
Traceback (most recent call last):
  File "./Port_Flap_Check.py", line 230, in <module>
    fp.write(dev.rpc.get_log(filename='messages').text)     #to save in local copy
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/rpcmeta.py", line 342, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py", line 31, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 770, in execute
    ignore_warning=ignore_warning)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py", line 116, in wrapper
    rsp = function(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 1321, in _rpc_reply
    return self._conn.rpc(rpc_cmd_e)._NCElement__doc
  File "/usr/local/lib/python2.7/dist-packages/ncclient/manager.py", line 172, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/ncclient/manager.py", line 232, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/ncclient/operations/third_party/juniper/rpc.py", line 44, in request
    return self._request(rpc)
  File "/usr/local/lib/python2.7/dist-packages/ncclient/operations/rpc.py", line 339, in _request
    return NCElement(self._reply, self._device_handler.transform_reply())
  File "/usr/local/lib/python2.7/dist-packages/ncclient/xml_.py", line 153, in __init__
    self.__doc = self.remove_namespaces(self.__result)
  File "/usr/local/lib/python2.7/dist-packages/ncclient/xml_.py", line 201, in remove_namespaces
    self.__root = etree.fromstring(str(self.__transform(etree.parse(StringIO(str(rpc_reply))))))
  File "src/lxml/lxml.etree.pyx", line 3442, in lxml.etree.parse (src/lxml/lxml.etree.c:81716)
  File "src/lxml/parser.pxi", line 1828, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:118859)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:119128)
  File "src/lxml/parser.pxi", line 1736, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:117808)
  File "src/lxml/parser.pxi", line 1102, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:112052)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105896)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:107604)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:106458)
  File "<string>", line 72326
lxml.etree.XMLSyntaxError: xmlSAX2Characters: huge text node, line 72326, column 30
---------------------------
file:
messages             Size: 10116342

Name: junos-eznc
Version: 2.1.5
Location: /usr/local/lib/python2.7/dist-packages
Requires: jinja2, scp, six, paramiko, netaddr, lxml, PyYAML, pyserial, ncclient

**Comment by stacywsmith** [comment]
Please see https://github.com/ncclient/ncclient/issues/185

You can apply the fix from here:
https://github.com/ncclient/ncclient/pull/186/files

This hasn't been committed to ncclient because it's not necessarily the ideal way to solve the problem. However, it will avoid your issue and work correctly.

--Stacy


On Aug 31, 2017, at 4:39 PM, njayarama <notifications@github.com<mailto:notifications@github.com>> wrote:


unable to pull huge file of 'messages' from device with rpc.get_log. what is a better solution to search 'log messages' from device?

code snippet:
dev = Device(host=ibx_fqdn, user=sw_user, passwd=sw_passwd).open()
dev.timeout = 3000
with open('local.log', 'w') as fp:
fp.write(dev.rpc.get_log(filename='messages').text) #to save in local copy
dev.close()

/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py:794: RuntimeWarning: An unknown exception occured - please report.
RuntimeWarning)
Traceback (most recent call last):
File "./Port_Flap_Check.py", line 230, in
fp.write(dev.rpc.get_log(filename='messages').text) #to save in local copy
File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/rpcmeta.py", line 342, in _exec_rpc
return self._junos.execute(rpc, **dec_args)
File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py", line 76, in wrapper
return function(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py", line 31, in wrapper
return function(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 770, in execute
ignore_warning=ignore_warning)
File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py", line 116, in wrapper
rsp = function(self, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 1321, in _rpc_reply
return self._conn.rpc(rpc_cmd_e)._NCElement__doc
File "/usr/local/lib/python2.7/dist-packages/ncclient/manager.py", line 172, in wrapper
return self.execute(op_cls, *args, **kwds)
File "/usr/local/lib/python2.7/dist-packages/ncclient/manager.py", line 232, in execute
raise_mode=self._raise_mode).request(*args, **kwds)
File "/usr/local/lib/python2.7/dist-packages/ncclient/operations/third_party/juniper/rpc.py", line 44, in request
return self._request(rpc)
File "/usr/local/lib/python2.7/dist-packages/ncclient/operations/rpc.py", line 339, in _request
return NCElement(self._reply, self.device_handler.transform_reply())
File "/usr/local/lib/python2.7/dist-packages/ncclient/xml.py", line 153, in init
self.__doc = self.remove_namespaces(self._result)
File "/usr/local/lib/python2.7/dist-packages/ncclient/xml.py", line 201, in remove_namespaces
self.__root = etree.fromstring(str(self.__transform(etree.parse(StringIO(str(rpc_reply))))))
File "src/lxml/lxml.etree.pyx", line 3442, in lxml.etree.parse (src/lxml/lxml.etree.c:81716)
File "src/lxml/parser.pxi", line 1828, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:118859)
File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:119128)
File "src/lxml/parser.pxi", line 1736, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:117808)
File "src/lxml/parser.pxi", line 1102, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:112052)
File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105896)
File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:107604)
File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:106458)
File "", line 72326
lxml.etree.XMLSyntaxError: xmlSAX2Characters: huge text node, line 72326, column 30

file:
messages Size: 10116342

Name: junos-eznc
Version: 2.1.5
Location: /usr/local/lib/python2.7/dist-packages
Requires: jinja2, scp, six, paramiko, netaddr, lxml, PyYAML, pyserial, ncclient

**Comment by njayarama** [comment]
Thank you for your prompt reply.
