### ISSUE TITLE
AttributeError exception when loading XML configuration

### ISSUE THREAD

**Issue by dmontagner** [Juniper/py-junos-eznc#799]
Hi there,

here is the xml configuration I am trying to load:

```
        <configuration>
                <protocols>
                    <mpls>
                        <label-switched-path>
                            <name>ABC</name>
                            <bandwidth>
                                <per-traffic-class-bandwidth>70m</per-traffic-class-bandwidth>
                            </bandwidth>
                        </label-switched-path>
                    </mpls>
                </protocols>
        </configuration>
```

> This configuration already exists in the router. I am just trying to update the bandwidth parameter.

The code used to load the configuration in the router is:

```
cu = Config(dev)
cu.load(config, "xml")
```

> The content of config is the XML content presented above.

When loading the configuration, I am getting this exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./frontend.py", line 155, in set_split_ratio
    provisionRouter(rtConn, rendered_fixed_cfg_update, "fixed config update", "xml")
  File "./frontend.py", line 184, in provisionRouter
    cu.load(config, cfgFormat)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/config.py", line 533, in load
    ignore_warning=ignore_warning)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/config.py", line 450, in try_load
    **rpc_xattrs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/rpcmeta.py", line 272, in load_config
    if contents.tag != 'configuration':
AttributeError: 'unicode' object has no attribute 'tag'
```

If I add a breakpoint in the code where it is throwing the exception, this is what I see:

```
dmontagner@ask1:~/app$ sudo python -m pdb ./frontend.py
> /home/dmontagner/app/frontend.py(7)<module>()
-> import sys
(Pdb) b /usr/local/lib/python2.7/dist-packages/jnpr/junos/rpcmeta.py:272
Breakpoint 1 at /usr/local/lib/python2.7/dist-packages/jnpr/junos/rpcmeta.py:272
(Pdb) cont

<... omitted for brevity ...>

> /usr/local/lib/python2.7/dist-packages/jnpr/junos/rpcmeta.py(272)load_config()
-> if contents.tag != 'configuration':
(Pdb) l 260,280
260  	        rpc = E('load-configuration', options)
261
262  	        if contents is None and 'url' in options:
263  	            pass
264  	        elif ('action' in options) and (options['action'] == 'set'):
265  	            rpc.append(E('configuration-set', contents))
266  	        elif ('format' in options) and (options['format'] == 'text'):
267  	            rpc.append(E('configuration-text', contents))
268  	        elif ('format' in options) and (options['format'] == 'json'):
269  	            rpc.append(E('configuration-json', contents))
270  	        else:
271  	            # otherwise, it's just XML Element
272 B->	            if contents.tag != 'configuration':
273  	                etree.SubElement(rpc, 'configuration').append(contents)
274  	            else:
275  	                rpc.append(contents)
276
277  	        return self._junos.execute(rpc, ignore_warning=ignore_warning)
278
279  	    # -----------------------------------------------------------------------
280  	    # cli
(Pdb) whatis(contents)
<type 'unicode'>
(Pdb) dir(contents)
['__add__', '__class__', '__contains__', '__delattr__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getslice__', '__gt__', '__hash__', '__init__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '_formatter_field_name_split', '_formatter_parser', 'capitalize', 'center', 'count', 'decode', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'index', 'isalnum', 'isalpha', 'isdecimal', 'isdigit', 'islower', 'isnumeric', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']
(Pdb) p contents
u'\n        <configuration>\n                <protocols>\n                    <mpls>\n                        <label-switched-path>\n                            <name>NFX1_FIXED</name>\n                            <bandwidth>\n                                <per-traffic-class-bandwidth>70m</per-traffic-class-bandwidth>\n                            </bandwidth>\n                        </label-switched-path>\n                    </mpls>\n                </protocols>\n        </configuration>\n        '
(Pdb) cont
[2017-11-29 11:03:24,867] ERROR in app: Exception on /set-split-ratio [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./frontend.py", line 155, in set_split_ratio
    provisionRouter(rtConn, rendered_fixed_cfg_update, "fixed config update", "xml")
  File "./frontend.py", line 184, in provisionRouter
    cu.load(config, cfgFormat)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/config.py", line 533, in load
    ignore_warning=ignore_warning)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/config.py", line 450, in try_load
    **rpc_xattrs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/rpcmeta.py", line 272, in load_config
    if contents.tag != 'configuration':
AttributeError: 'unicode' object has no attribute 'tag'
2017-11-29 11:03:24,879	INFO -- MainProcess _internal.py:87 -- 192.168.122.1 - - [29/Nov/2017 11:03:24] "POST /set-split-ratio HTTP/1.1" 500 -
```

**Comment by dmontagner** [comment]
The problem is that at this stage, the configuration is not a XML tree yet.

My code is following this: [https://www.juniper.net/documentation/en_US/junos-pyez/topics/task/program/junos-pyez-program-configuration-data-loading.html](https://www.juniper.net/documentation/en_US/junos-pyez/topics/task/program/junos-pyez-program-configuration-data-loading.html)

**Comment by dmontagner** [comment]
ok. I found the problem. Looks like in the past the following syntax was supported:

```
cu.load(config, "xml")
```

But looks like now the only supported syntax is:

```
cu.load(config, format='xml')
```
