### ISSUE TITLE
ConnectionResetError appears, how to handle it?

### ISSUE THREAD

**Issue by depamu** [Juniper/py-junos-eznc#815]
Hello,
when I run my script to get the information about the "Last flapped" status, the program stops at the following Interface with a ConnectionResetError (s. below)...

Can someone please, help me out here?
Thank you !
 
```ge-0/0/19: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 2003, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/packet.py", line 353, in readline
    buf += self._read_timeout(timeout)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/packet.py", line 540, in _read_timeout
    x = self.__socket.recv(128)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "junos_cmd_test.py", line 61, in <module>
    print(get_last_flapped(dev))
  File "junos_cmd_test.py", line 41, in get_last_flapped
    output = sh_cmd(dev, cmd)
  File "junos_cmd_test.py", line 13, in sh_cmd
    with StartShell(dev) as shell:
  File "/usr/local/lib/python3.5/dist-packages/jnpr/junos/utils/start_shell.py", line 162, in __enter__
    self.open()
  File "/usr/local/lib/python3.5/dist-packages/jnpr/junos/utils/start_shell.py", line 93, in open
    password=junos._auth_password,
  File "/usr/local/lib/python3.5/dist-packages/paramiko/client.py", line 392, in connect
    t.start_client(timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 545, in start_client
    raise e
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 1856, in run
    self._check_banner()
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 2008, in _check_banner
    'Error reading SSH protocol banner' + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer
```

**Comment by vnitinv** [comment]
@depamu We will need your script snippet to help you out.

**Comment by rahkumar651991** [comment]
Closing it due to inactivity.
