### ISSUE TITLE
Config.diff() does not handle RpcTimeoutError properly

### ISSUE THREAD

**Issue by vozhyk-** [Juniper/py-junos-eznc#830]
If a timeout happens when calling `.pdiff()` on a config table instance, the `RpcTimeoutError` is caught (as an `RpcError`) at https://github.com/Juniper/py-junos-eznc/blob/5d2f16cf62155e12a68e0258ea20bc174c749203/lib/jnpr/junos/utils/config.py#L227-L228, but the code expects it to have `['severity']`, which it apparently doesn't, and a `TypeError` is thrown.

Expected behavior: the `RpcTimeoutError` is thrown up to the caller.

`junos-eznc` version: 2.1.7.

```
>>> t.pdiff()
Traceback (most recent call last):
  File "<redacted project directory>/.venv/lib64/python3.6/site-packages/jnpr/junos/device.py", line 770, in execute
    ignore_warning=ignore_warning)
  File "<redacted project directory>/.venv/lib64/python3.6/site-packages/jnpr/junos/decorators.py", line 116, in wrapper
    rsp = function(self, *args, **kwargs)
  File "<redacted project directory>/.venv/lib64/python3.6/site-packages/jnpr/junos/device.py", line 1321, in _rpc_reply
    return self._conn.rpc(rpc_cmd_e)._NCElement__doc
  File "<redacted project directory>/.venv/lib64/python3.6/site-packages/ncclient/manager.py", line 172, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "<redacted project directory>/.venv/lib64/python3.6/site-packages/ncclient/manager.py", line 232, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "<redacted project directory>/.venv/lib64/python3.6/site-packages/ncclient/operations/third_party/juniper/rpc.py", line 44, in request
    return self._request(rpc)
  File "<redacted project directory>/.venv/lib64/python3.6/site-packages/ncclient/operations/rpc.py", line 343, in _request
    raise TimeoutExpiredError('ncclient timed out while waiting for an rpc reply.')
ncclient.operations.errors.TimeoutExpiredError: ncclient timed out while waiting for an rpc reply.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<redacted project directory>/.venv/lib64/python3.6/site-packages/jnpr/junos/utils/config.py", line 225, in diff
    compare='rollback', rollback=str(rb_id), format='text'
  File "<redacted project directory>/.venv/lib64/python3.6/site-packages/jnpr/junos/rpcmeta.py", line 345, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "<redacted project directory>/.venv/lib64/python3.6/site-packages/jnpr/junos/decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "<redacted project directory>/.venv/lib64/python3.6/site-packages/jnpr/junos/decorators.py", line 31, in wrapper
    return function(*args, **kwargs)
  File "<redacted project directory>/.venv/lib64/python3.6/site-packages/jnpr/junos/device.py", line 774, in execute
    raise EzErrors.RpcTimeoutError(self, rpc_cmd_e.tag, self.timeout)
jnpr.junos.exception.RpcTimeoutError: RpcTimeoutError(host: lan-switch, cmd: get-configuration, timeout: 30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<redacted project directory>/.venv/lib64/python3.6/site-packages/jnpr/junos/utils/config.py", line 249, in pdiff
    print (self.diff(rb_id))
  File "<redacted project directory>/.venv/lib64/python3.6/site-packages/jnpr/junos/utils/config.py", line 228, in diff
    if (err.rpc_error['severity'] == 'warning' and
TypeError: 'NoneType' object is not subscriptable
```

**Comment by vnitinv** [comment]
Fixed via #840
