### ISSUE TITLE
Console Class Juniper Junos Console : Login State machine failure for WR Based Linux Hardware 

### ISSUE THREAD

**Issue by mamathac** [Juniper/py-junos-eznc#845]
The python script is trying to connect to a WR Based Linux Hardware via Console and do load operations.
Gather facts was set to True and False both, both the times the script returned login_sm failure error even for root user.

Script:
from jnpr.junos.console import Console
from jnpr.junos.utils.config import Config
import logging

logging.basicConfig(level=logging.INFO)

# Creating an instance to login to a device in console mode
with Console(host='CONSOLE_IP', user='USER', password='PASSWORD', mode='telnet', port='', gather_facts=True) as dev:
    print (dev.facts)
    print (dev.cli("show version", warning=False))
    cu = Config(dev)
    print ("********** Loading the configuration **********");
    cu.load(path='/root/config-example.set', merge=True)
    cu.pdiff()
    print ("********** Commiting the configuration **********");
    cu.commit()

RESULT:
ERROR:jnpr.junos.console:ERROR:  login:login_sm_failure

ERROR:jnpr.junos.console:
Complete traceback message: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/console.py", line 189, in open
    self._tty_login()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/console.py", line 285, in _tty_login
    self._tty.login()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/transport/tty.py", line 111, in login
    self._login_state_machine()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/transport/tty.py", line 273, in _login_state_machine
    self._login_state_machine(attempt + 1)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/transport/tty.py", line 273, in _login_state_machine
    self._login_state_machine(attempt + 1)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/transport/tty.py", line 273, in _login_state_machine
    self._login_state_machine(attempt + 1)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/transport/tty.py", line 273, in _login_state_machine
    self._login_state_machine(attempt + 1)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/transport/tty.py", line 273, in _login_state_machine
    self._login_state_machine(attempt + 1)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/transport/tty.py", line 273, in _login_state_machine
    self._login_state_machine(attempt + 1)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/transport/tty.py", line 273, in _login_state_machine
    self._login_state_machine(attempt + 1)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/transport/tty.py", line 273, in _login_state_machine
    self._login_state_machine(attempt + 1)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/transport/tty.py", line 273, in _login_state_machine
    self._login_state_machine(attempt + 1)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/transport/tty.py", line 273, in _login_state_machine
    self._login_state_machine(attempt + 1)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/transport/tty.py", line 179, in _login_state_machine
    raise RuntimeError('login_sm_failure')
RuntimeError: login_sm_failure

Traceback (most recent call last):
  File "/root/TC33.py", line 8, in <module>
    with Console(host='10.216.9.22', user='root', password='*****', mode='telnet', port='', gather_facts=False) as dev:
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/console.py", line 302, in __enter__
    self._conn = self.open()
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/console.py", line 195, in open
    raise err
RuntimeError: login_sm_failure

**Comment by jnpr-bowen** [comment]
Your reference to "a WR Based Linux Hardware" suggests that this may be trying to connect to something like a NFX device. If that is the case, the console login processing may not be fully implemented. Can you provide a sample of a telnet session to the console that ends with the junos cli user prompt ("host_name > ")?

**Comment by mamathac** [comment]
:~> telnet <hostname>-con
Trying <x.x.x.x>...
Connected to x.x.x.x.englab.juniper.net.
Escape character is '^]'.

There is no hot key to close the connection.

Juniper Linux Distribution 2.2.1 <hostname> ttyS0

<hostname>-re0 login: root
Password:
Last login: Mon Jul 23 20:10:30 PDT 2018 from 10.222.38.87 on pts/1
--- JUNOS builder Linux re 4.8.24-WR2.2.1_standard #28 SMP PREEMPT Thu Jul 12 06:14:07 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
root@<hostname>-re0:~# cli
root@<hostname>-re0>

**Comment by vnitinv** [comment]
@mamathac  was due to internal PR #1365520 wrt <file-list> rpc. Closing the issue. Please re-open if the issue still exists.
