### ISSUE TITLE
File System class FS : ls <dir> returns error.

### ISSUE THREAD

**Issue by mamathac** [Juniper/py-junos-eznc#846]
Using jnpr.junos.utils.fs to perform 'ls' on a directory.

Operation : ls /var/tmp

```
Python Script:
from jnpr.junos.utils.fs import FS
from jnpr.junos import Device
import pprint as pprint

dev = Device(host='xxxx', user='xxxx', password='xxxx')
dev.open()

fs = FS(dev)
pprint(fs.ls('/var/tmp'))

dev.close()
```

Result:
Python2.9

> python2.7 11_file_system.py
> Traceback (most recent call last):
>   File "11_file_system.py", line 9, in <module>
>     pprint(fs.ls('/var/tmp'))
>   File "/etc/ansible/ANS_virtualenv/local/lib/python2.7/site-packages/jnpr/junos/utils/fs.py", line 219, in ls
>     if not xdir.get('name'):
> AttributeError: 'NoneType' object has no attribute 'get'
> 

Python3.4
> (ANS_virtualenv)user@host:<path>#  python3.4 11_file_system.py
> Traceback (most recent call last):
>   File "11_file_system.py", line 9, in <module>
>     pprint(fs.ls('/var/tmp'))
>   File "/usr/local/lib/python3.4/dist-packages/jnpr/junos/utils/fs.py", line 219, in ls
>     if not xdir.get('name'):

Env on host:
asn1crypto==0.23.0
bcrypt==3.1.4
cffi==1.11.2
cryptography==2.1.3
enum34==1.1.6
idna==2.6
ipaddress==1.0.18
Jinja2==2.10
junos-eznc==2.1.9.dev0
lxml==4.1.1
MarkupSafe==1.0
ncclient==0.5.3
netaddr==0.7.19
paramiko==2.4.0
pyasn1==0.3.7
pycparser==2.18
PyNaCl==1.2.0
pyserial==3.4
PyYAML==3.12
scp==0.10.2
six==1.11.0

# python2.7 -c 'import jnpr.junos; print jnpr.junos.__version__'
2.1.9.dev0

**Comment by mamathac** [comment]
PR #1365520 is fixed and closed.
fl.ls works as expected 

('\nList of files in /var/tmp:', {'files': ['JC_Instrumentation', 'baseline-config.conf', 'diff.cfg', 'fabspoke_fchip.log', 'fabspoke_pfe.log', 'pyez-archive.tgz'], 'path': '/var/tmp/', 'type': 'dir', 'file_count': 6, 'size': 89802})
