### ISSUE TITLE
Console Class Juniper Junos Console : Login State machine failure for WR Based Linux Hardware

### ISSUE THREAD

**Issue by mamathac** [Juniper/py-junos-eznc#888]
Issue still persists:
Original Issue which was closed.
https://github.com/Juniper/py-junos-eznc/issues/845

Current output with latest Pyez:
INFO:jnpr.junos.tty:TTY: connecting to TTY:IP ADDRESS  ...
INFO:jnpr.junos.tty:TTY: logging in......
ERROR:jnpr.junos.console:ERROR:  login:login_sm_failure

ERROR:jnpr.junos.console:
Complete traceback message: Traceback (most recent call last):
  File "/Users/mamathac/PycharmProjects/Ansible/venv/lib/python2.7/site-packages/jnpr/junos/console.py", line 211, in open
    self._tty_login()
  File "/Users/mamathac/PycharmProjects/Ansible/venv/lib/python2.7/site-packages/jnpr/junos/console.py", line 316, in _tty_login
    self._tty.login()
  File "/Users/mamathac/PycharmProjects/Ansible/venv/lib/python2.7/site-packages/jnpr/junos/transport/tty.py", line 111, in login
    self._login_state_machine()
  File "/Users/mamathac/PycharmProjects/Ansible/venv/lib/python2.7/site-packages/jnpr/junos/transport/tty.py", line 273, in _login_state_machine
    self._login_state_machine(attempt + 1)
  File "/Users/mamathac/PycharmProjects/Ansible/venv/lib/python2.7/site-packages/jnpr/junos/transport/tty.py", line 273, in _login_state_machine
    self._login_state_machine(attempt + 1)
  File "/Users/mamathac/PycharmProjects/Ansible/venv/lib/python2.7/site-packages/jnpr/junos/transport/tty.py", line 273, in _login_state_machine
    self._login_state_machine(attempt + 1)
  File "/Users/mamathac/PycharmProjects/Ansible/venv/lib/python2.7/site-packages/jnpr/junos/transport/tty.py", line 273, in _login_state_machine
    self._login_state_machine(attempt + 1)
  File "/Users/mamathac/PycharmProjects/Ansible/venv/lib/python2.7/site-packages/jnpr/junos/transport/tty.py", line 273, in _login_state_machine
    self._login_state_machine(attempt + 1)
  File "/Users/mamathac/PycharmProjects/Ansible/venv/lib/python2.7/site-packages/jnpr/junos/transport/tty.py", line 273, in _login_state_machine
    self._login_state_machine(attempt + 1)
  File "/Users/mamathac/PycharmProjects/Ansible/venv/lib/python2.7/site-packages/jnpr/junos/transport/tty.py", line 273, in _login_state_machine
    self._login_state_machine(attempt + 1)
  File "/Users/mamathac/PycharmProjects/Ansible/venv/lib/python2.7/site-packages/jnpr/junos/transport/tty.py", line 273, in _login_state_machine
    self._login_state_machine(attempt + 1)
  File "/Users/mamathac/PycharmProjects/Ansible/venv/lib/python2.7/site-packages/jnpr/junos/transport/tty.py", line 273, in _login_state_machine
    self._login_state_machine(attempt + 1)
  File "/Users/mamathac/PycharmProjects/Ansible/venv/lib/python2.7/site-packages/jnpr/junos/transport/tty.py", line 273, in _login_state_machine
    self._login_state_machine(attempt + 1)
  File "/Users/mamathac/PycharmProjects/Ansible/venv/lib/python2.7/site-packages/jnpr/junos/transport/tty.py", line 179, in _login_state_machine
    raise RuntimeError('login_sm_failure')
RuntimeError: login_sm_failure

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mamathac/PycharmProjects/Ansible/venv/lib/python2.7/site-packages/jnpr/junos/console.py", line 333, in __enter__
    self._conn = self.open()
  File "/Users/mamathac/PycharmProjects/Ansible/venv/lib/python2.7/site-packages/jnpr/junos/console.py", line 217, in open
    raise err
RuntimeError: login_sm_failure
>>> 

Script:
from jnpr.junos.console import Console
from jnpr.junos.utils.config import Config
import logging

logging.basicConfig(level=logging.INFO)

with Console(host='IP', user='USER', password='PASSWORD', mode='telnet', port='PORT', gather_facts=False) as dev:
    print (dev.facts)

>> Tried with both gather_facts=False and gather_facts=True:

Telnet to that port with given username and password works!

_Originally posted by @vnitinv in https://github.com/Juniper/py-junos-eznc/issues/845#issuecomment-410167343_

**Comment by mamathac** [comment]
Issue seems to be fixed.
/Users/mamathac/PycharmProjects/Ansible/venv/bin/python /Users/mamathac/PycharmProjects/Ansible/venv/PyEZ/Login_Console.py
INFO:jnpr.junos.tty:TTY: connecting to TTY:IP:PORT ...
INFO:jnpr.junos.tty:TTY: logging in......
INFO:jnpr.junos.tty:TTY: OK.....starting NETCONF
INFO:jnpr.junos.tty_netconf:Calling rpc: <rpc><get-route-engine-information/></rpc>
INFO:jnpr.junos.tty_netconf:Calling rpc: <rpc><file-list><path>~</path></file-list></rpc>
INFO:jnpr.junos.tty_netconf:Calling rpc: <rpc><get-chassis-inventory/></rpc>
INFO:jnpr.junos.tty_netconf:Calling rpc: <rpc><file-show><filename>/usr/share/cevo/cevo_version</filename></file-show></rpc>
INFO:jnpr.junos.tty_netconf:Calling rpc: <rpc><get-system-nodes-information/></rpc>
INFO:jnpr.junos.tty_netconf:Calling rpc: <rpc><get-configuration commit-scripts="apply" inherit="inherit" database="committed"><configuration>
            <system>
                <domain-name/>
             </system>
        </configuration></get-configuration></rpc>
INFO:jnpr.junos.tty_netconf:Calling rpc: <rpc><command>show version invoke-on all-routing-engines</command></rpc>
INFO:jnpr.junos.tty_netconf:Calling rpc: <rpc><get-software-information><node>all</node></get-software-information></rpc>
INFO:jnpr.junos.tty_netconf:Calling rpc: <rpc><get-chassis-cluster-status/></rpc>
INFO:jnpr.junos.tty_netconf:Calling rpc: <rpc><get-ethernet-switching-table-information><summary/></get-ethernet-switching-table-information></rpc>
INFO:jnpr.junos.tty_netconf:Calling rpc: <rpc><command>show bridge mac-table count</command></rpc>
INFO:jnpr.junos.tty_netconf:Calling rpc: <rpc><get-virtual-chassis-information/></rpc>
INFO:jnpr.junos.tty_netconf:Calling rpc: <rpc><command format="text">show version</command></rpc>
{'2RE': False, 'HOME': '/var/home/regress', 'RE0': {'status': 'OK', 'last_reboot_reason': 'Power On Reset', 'model': 'RE-QFX5200-32C-32Q', 'up_time': '4 hours, 34 minutes, 6 seconds', 'mastership_state': 'Master'}, 'RE1': None, 'RE_hw_mi': False, 'current_re': ['re0'], 'domain': 'englab.juniper.net', 'fqdn': None, 'hostname': None, 'hostname_info': None, 'ifd_style': 'CLASSIC', 'junos_info': None, 'master': 'RE0', 'model': None, 'model_info': None, 'personality': None, 're_info': {'default': {'default': {'status': 'OK', 'last_reboot_reason': 'Power On Reset', 'model': 'RE-QFX5200-32C-32Q', 'mastership_state': 'Master'}, '0': {'status': 'OK', 'last_reboot_reason': 'Power On Reset', 'model': 'RE-QFX5200-32C-32Q', 'mastership_state': 'Master'}}}, 're_master': {'default': '0'}, 'serialnumber': 'WN0218310452', 'srx_cluster': None, 'srx_cluster_id': None, 'srx_cluster_redundancy_group': None, 'switch_style': 'NONE', 'vc_capable': False, 'vc_fabric': None, 'vc_master': None, 'vc_mode': None, 'version': None, 'version_RE0': None, 'version_RE1': None, 'version_info': None, 'virtual': None}
INFO:jnpr.junos.tty_netconf:Calling rpc: <rpc><load-configuration action="set" format="text"><configuration-set>set groups global system syslog host log kernel info
set groups global system syslog host log any notice
set groups global system syslog host log pfe info
set groups global system syslog host log interactive-commands any
set groups global system syslog file messages kernel info
set groups global system syslog file messages any notice
set groups global system syslog file messages authorization info
set groups global system syslog file messages pfe info
set groups global system syslog file messages archive world-readable
set groups global system syslog file security interactive-commands any
set groups global system syslog file security archive world-readable
</configuration-set></load-configuration></rpc>

Model: qfx5200-32c-32q
Junos: 18.4-20181009.1
Junos Package: junos-linux-install-qfx-ms-fixed-x86-64-18.4-20181009.1.iso
Yocto: 2.2.1
Linux Kernel: 4.8.24-WR2.2.1_standard

********** Loading the configuration **********
INFO:jnpr.junos.tty_netconf:Calling rpc: <rpc><get-configuration compare="rollback" rollback="0" format="text"/></rpc>
None
INFO:jnpr.junos.tty_netconf:Calling rpc: <rpc><commit-configuration/></rpc>
********** Commiting the configuration **********
INFO:jnpr.junos.tty:logout: logging out.....
INFO:jnpr.junos.tty_netconf:Calling rpc: <rpc><close-session/></rpc>

Process finished with exit code 0

**Comment by mamathac** [comment]
Verified and found  fixed

**Comment by shivintwrk** [comment]
Using open() with serial connection throws the following error which prevents any configurations to be done using serial. This platform is Windows10. Is this due to any limitation regarding serial connection?

INFO:jnpr.junos.tty:TTY: connecting to TTY:COM ...
INFO:jnpr.junos.tty:TTY: logging in......
WARNING:jnpr.junos.tty:login_warn: Shell login was open!!
INFO:jnpr.junos.tty:TTY: OK.....starting NETCONF
ERROR:jnpr.junos.console:Exception occurred: login:fileno

Traceback (most recent call last):
  File "c:/Users/bcng63/Documents/NITRO/FirewallPrep1.py", line 212, in <module>
    main()
  File "c:/Users/bcng63/Documents/NITRO/FirewallPrep1.py", line 182, in main
    cu = Config(dev.open())
  File "C:\Python37\lib\site-packages\jnpr\junos\console.py", line 222, in open
    raise ex
  File "C:\Python37\lib\site-packages\jnpr\junos\console.py", line 212, in open
    self._tty_login()
  File "C:\Python37\lib\site-packages\jnpr\junos\console.py", line 319, in _tty_login
    self._tty.login()
  File "C:\Python37\lib\site-packages\jnpr\junos\transport\tty.py", line 116, in login
    self.nc.open(at_shell=self.at_shell)
  File "C:\Python37\lib\site-packages\jnpr\junos\transport\tty_netconf.py", line 68, in open
    self.hello = self._receive()
  File "C:\Python37\lib\site-packages\jnpr\junos\transport\tty_netconf.py", line 142, in _receive
    raise err
  File "C:\Python37\lib\site-packages\jnpr\junos\transport\tty_netconf.py", line 140, in _receive
    rd, wt, err = select.select([self._tty._rx], [], [], 0.1)
