### ISSUE TITLE
Junos facts JSON serialization got broken

### ISSUE THREAD

**Issue by dineshbaburam91** [Juniper/py-junos-eznc#901]
```
import json
import sys
from jnpr.junos import Device
from jnpr.junos.exception import ConnectError
 
dev = Device('router1.example.net')
try:
    dev.open()
except ConnectError as err:
    print ("Cannot connect to device: {0}".format(err))
    sys.exit(1)
 
print (json.dumps(dev.facts))
dev.close()
```
#### Output
Traceback (most recent call last):
  File "junos-pyez-2.2-get-facts.py", line 27, in <module>
    print (json.dumps(dev.facts))
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/factory/to_json.py", line 57, in default
    obj = super(PyEzJSONEncoder, self).default(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: {'2RE': True,
'HOME': '/var/home/abc',
'RE0': {'last_reboot_reason': 'Router rebooted after a normal shutdown.',
         'mastership_state': 'master',
         'model': 'XXX',
         'status': 'OK',
         'up_time': '1 hour, 12 minutes, 23 seconds'},
[output omitted]
'virtual': False} is not JSON serializable

**Comment by dineshbaburam91** [comment]
The issue is fixed in pull request [902](https://github.com/Juniper/py-junos-eznc/pull/902) and status of pull reuest is under review required.
