### ISSUE TITLE
SRX1500 clustered / dev.facts empty values

### ISSUE THREAD

**Issue by lboue** [Juniper/py-junos-eznc#906]
Hello,

I have a SRX1500 chassis cluster firewall running Junos 15.1X49-D160.2:
```
srx> show chassis cluster status 
...
 
Cluster ID: 1
Node   Priority Status         Preempt Manual   Monitor-failures

Redundancy group: 0 , Failover count: 1
node0  100      primary        no      no       None           
node1  50       secondary      no      no       None           

Redundancy group: 1 , Failover count: 1
node0  100      primary        yes     no       None           
node1  50       secondary      yes     no       None
```

I am facing an issue when I get call dev.facts. Every parameter is set to 'None':
```
{'2RE': None,
 'HOME': None,
 'RE0': None,
 'RE1': None,
 'RE_hw_mi': None,
 'current_re': None,
 'domain': None,
 'fqdn': None,
 'hostname': None,
 'hostname_info': None,
 'ifd_style': 'CLASSIC',
 'junos_info': None,
 'master': None,
 'model': None,
 'model_info': None,
 'personality': None,
 're_info': None,
 're_master': None,
 'serialnumber': None,
 'srx_cluster': None,
 'srx_cluster_id': None,
 'srx_cluster_redundancy_group': None,
 'switch_style': None,
 'vc_capable': None,
 'vc_fabric': None,
 'vc_master': None,
 'vc_mode': None,
 'version': None,
 'version_RE0': None,
 'version_RE1': None,
 'version_info': None,
 'virtual': None}
```

I  have the same issue when I try to call the reboot method:
```
# Create an instance of SW
sw = SW(dev)

logging.info('Software installation complete. Rebooting')
rsp = sw.reboot()
```

```
dev.facts['current_re']: None
Traceback (most recent call last):
  File "pyez-junos-srx-reboot.py", line 29, in <module>
    sw = SW(dev)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\lib\site-packages\jnpr\junos\utils\sw.py", line 92, in __init__
    'localre' in dev.facts['current_re'])
TypeError: argument of type 'NoneType' is not iterable
```

I don't understand what cause this issue. Can you help me ?

Regards,
Ludovic

**Comment by dineshbaburam91** [comment]
Whats the PyEZ version in use?
share the o/p for 
pip list | grep junos-eznc

**Comment by vnitinv** [comment]
@lboue We are trying to get similar setup in local lab to debug the issue. Will keep you posted.

**Comment by vnitinv** [comment]
we are not able to replicate this. Can you share netconf trace.

**Comment by rsmekala** [comment]
Marking as inactive. Will close it in a week.

**Comment by rsmekala** [comment]
Closing the issue. Please do reopen if required ✌️
