### ISSUE TITLE
Juniper on-box script : StatShelll - credentials error

### ISSUE THREAD

**Issue by brahmastra2016** [Juniper/py-junos-eznc#908]
For on-box pyhton script we just use "dev = dev = Device()" to connect but it throw exception error since start shell module has the user/password as required parameters.

root@Nemo> op test.py

Traceback (most recent call last):
  File "/var/db/scripts/op/test.py", line 104, in <module>
main()
  File "/var/db/scripts/op/test.py", line 78, in main
with StartShell(dev) as ss:
  File "../../../../../../../../src/dist/python-add-ons/junos-eznc/lib/jnpr/junos/utils/start_shell.py", line 170, in __enter__
  File "../../../../../../../../src/dist/python-add-ons/junos-eznc/lib/jnpr/junos/utils/start_shell.py", line 102, in open
RuntimeError
:
**StartShell requires user credentials**

error: op script failed: /var/db/scripts/op/test.py

**Comment by carbinefreak** [comment]
Any movement on this? As of junos-srxsme-23.4R2-S3 its still not supported on the SRX3XX series.
