### ISSUE TITLE
forcehost not available in sw.install

### ISSUE THREAD

**Issue by samascience** [Juniper/py-junos-eznc#929]
Traceback (most recent call last):
  File "upgrade_junQFX5100_sama_v1.py", line 14, in <module>
    ok = sw.install(package=pkg, validate=True, progress=True, checksum_algorithm='md5', cleanfs=True, cleanfs_timeout=300, checksum_timeout=300, vmhost=True )
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/sw.py", line 891, in install
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/utils/sw.py", line 239, in pkgadd
    **kvargs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/rpcmeta.py", line 345, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py", line 23, in wrapper
    result = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 794, in execute    errs=ex)
jnpr.junos.exception.RpcError: RpcError(severity: warning, bad_element: None, message: Package /var/tmp/jinstall-host-qfx-5-flex-17.3R3-S3.3-limited-signed.tgz not supported, please try system command)

**Comment by vnitinv** [comment]
Sorry for such a log delay.

Can you run your script with log enables and share the logs. 

adding these 2 lines in the script will help
```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by rahkumar651991** [comment]
closing due to inactivity
