### ISSUE TITLE
`ssh_private_key_file` is broken

### ISSUE THREAD

**Issue by ntwrkguru** [Juniper/py-junos-eznc#936]
The `ssh_private_key_file` feature appears to be broken.

Repro Steps:

1. Create new key pair
    ```$ ssh-keygen
    Generating public/private rsa key pair.
    Enter file in which to save the key (/Users/ssteiner/.ssh/id_rsa): /Users/ssteiner/.ssh/pyez-test
    Enter passphrase (empty for no passphrase): 
    Enter same passphrase again: 
    Your identification has been saved in /Users/ssteiner/.ssh/pyez-test.
    Your public key has been saved in /Users/ssteiner/.ssh/pyez-test.pub.
    The key fingerprint is:
    SHA256:VGRxYfSy+0hipyr0tWwAhUH+RxHp9YCJPywWlh3Tnmw ssteiner@ssteiner-mbp
    The key's randomart image is: <snipped>
2. Add user and public key to Junos device
    ````# show system login user pyez-test 
    uid 2003;
    class super-user;
    authentication {
        ssh-rsa "ssh-rsa     AAAAB3NzaC1yc2EAAAADAQABAAABAQDv3JPDI/XV7r9RUG0jiNMt6YzBxRErTy9EK8pUQQI7OwgCIVOhaOoYSsK8HPEyzPYoBTQMGdvZYErSOnXt79Xl8gVZL35WPGAVRsRQaXS64rn4oUWaKbCriPQ66ZmQAeLvrnV3aclPATh4p6SWcwlycISu84lXMr+0M6NJZ96vMMnjgipdXR8quuyn0ox4C998YC6DyEBSxNARaBN6K9rJ93f2XknSxjRroFAzR2p9nqs4mfG3oE51flWXbg6RYqR4TsJnAZ0PJu+69W+FOzbF4WIDJe6MTd0HPhaaSvDpWl27DRyJN2iNk+AxYTIudeijWfixPCVY1Qq1brGraT2N ssteiner@ssteiner-mbp"; ## SECRET-DATA
    }
3. Test using `ssh -i`
    ````$ ssh -i /Users/ssteiner/.ssh/pyez-test pyez-test@192.168.1.202
    --- JUNOS 12.3R12.4 built 2016-01-20 04:27:03 UTC
    {master:0}
4. Test using python shell
    ```ssteiner-mbp:Downloads ssteiner$ python2
    Python 2.7.16 (default, Mar  4 2019, 09:01:38) 
    [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from jnpr.junos import Device
    >>> dev = Device(host='192.168.1.202', user='pyez-test', ssh_private_key_file='/Users/ssteiner/.ssh/pyez-test', port=22)
    >>> dev.open()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jnpr/junos/device.py", line 1265, in open
        raise EzErrors.ConnectAuthError(self)
    jnpr.junos.exception.ConnectAuthError: ConnectAuthError(192.168.1.202)
    >>>

**Comment by ntwrkguru** [comment]
This is caused by a newer version of openssh on MacOS Mojave and greater (see this [post](https://serverfault.com/questions/939909/ssh-keygen-does-not-create-rsa-private-key) for reference). The solution is to create the keys specifically using the PEM format (`ssh-keygen -m PEM -t rsa -b 4096`) or convert the existing _new style_ key using the command, `ssh-keygen -p -m PEM -f ~/.ssh/current_new_key_filename`

**Comment by gabrieldslacerda** [comment]
Just reporting that this issue still exists, but due to Paramiko's issue probably: https://github.com/ncclient/ncclient/issues/526. As they didn't fix the problem yet, people might still find this problem, as I did.
