### ISSUE TITLE
Empty or wrong ephemeral database instance causes PyEZ script to fail

### ISSUE THREAD

**Issue by rsmekala** [Juniper/py-junos-eznc#953]
Use the following snippet to generate the error:

eph2: Is the non-existent or empty ephemeral instance
```
from jnpr.junos.device import Device
from jnpr.junos.utils.config import Config
from lxml import etree

# For getting ephemeral configuration
with Device('xx.xx.xx.xx', user='user', password='passwd') as dev:
    reply = dev.rpc.get_config(options={'database': 'ephemeral', 'ephemeral-instance': 'eph2'})
    print(etree.tostring(reply))
```

The following error is generated as the method currently returns `True`
```
Traceback (most recent call last):
  File "/Users/rsmekala/PycharmProjects/salt/salt-states-examples/getConfig.py", line 8, in <module>
    print(etree.tostring(reply))
  File "src/lxml/etree.pyx", line 3359, in lxml.etree.tostring
TypeError: Type 'bool' cannot be serialized.
```

**Comment by chidanandpujar** [comment]
Expected behavior when ephemeral instance is not configured or empty , the rpc open-configuration by design returns empty tags , this can not be handled in lxml.etree , so you can handle this behavior using try and except .
```
from jnpr.junos.device import Device
from jnpr.junos.utils.config import Config
from lxml import etree

with Device('xx.xx.xx.xx', user='xxxxx', password='yyyyyy') as dev:
    reply = dev.rpc.get_config(options={'database': 'ephemeral', 'ephemeral-instance': 'eph500'})
    try:
        print(etree.tostring(reply))
    except TypeError as err:
        print("Ephemeral instance is empty or not configured on the Device ");
```
python3 eph_bug1.py
Ephemeral instance is empty or not configured on the Device
