### ISSUE TITLE
rpc for "request chassis routing-engine master switch"

### ISSUE THREAD

**Issue by iliyaz144** [Juniper/py-junos-eznc#982]
HI there, 
Can you please tell me the right RPC for performing swithover "request chassis routing-engine master switch ".

When ever i perform the above operation, i get many errors and exceptions.

Can you pls tell me the right rpc?

**Comment by vnitinv** [comment]
@iliyaz144 Can you please share errors and exception. RPC for given command is 
request-chassis-routing-engine-switch, so the call should be `dev.rpc.request_chassis_routing_engine_switch()`
let me know if this doesnt work for you

**Comment by iliyaz144** [comment]
HI nitin, 
I have tried the way you have suggested, but it throws an error below:
**>>> vpn.rpc.request_chassis_routing_engine_switch()
Traceback (most recent call last):
  File "C:\Python37\Lib\site-packages\jnpr\junos\device.py", line 799, in execute
    'filter_xml'))
  File "C:\Python37\Lib\site-packages\jnpr\junos\decorators.py", line 116, in wrapper
    rsp = function(self, *args, **kwargs)
  File "C:\Python37\Lib\site-packages\jnpr\junos\device.py", line 1381, in _rpc_reply
    return self._conn.rpc(rpc_cmd_e, filter_xml)._NCElement__doc
  File "C:\Python37\Lib\site-packages\ncclient\manager.py", line 236, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "C:\Python37\Lib\site-packages\ncclient\operations\third_party\juniper\rpc.py", line 52, in request
    return self._request(rpc)
  File "C:\Python37\Lib\site-packages\ncclient\operations\rpc.py", line 337, in _request
    raise self._error
  File "C:\Python37\Lib\site-packages\ncclient\transport\ssh.py", line 498, in run
    raise SessionCloseError(self._buffer.getvalue())
ncclient.transport.errors.SessionCloseError: Unexpected session close
IN_BUFFER: `b'<nc:rpc-reply  xmlns:junos="http://xml.juniper.net/junos/18.4R1/junos" xmlns:nc="urn:ietf:params:xml:ns:ne
tconf:base:1.0" message-id="urn:uuid:483c0c58-f75d-4357-a600-0f4b3898c2d3">\n<chassis-routing-engine-state>\n<message>Re
solving mastership...\n</message>\n<message>Complete. The other routing engine becomes the master.\n</message>\n'`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\Lib\site-packages\jnpr\junos\rpcmeta.py", line 346, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "C:\Python37\Lib\site-packages\jnpr\junos\decorators.py", line 76, in wrapper
    return function(*args, **kwargs)
  File "C:\Python37\Lib\site-packages\jnpr\junos\decorators.py", line 31, in wrapper
    return function(*args, **kwargs)
  File "C:\Python37\Lib\site-packages\jnpr\junos\device.py", line 805, in execute
    raise EzErrors.ConnectClosedError(self)
jnpr.junos.exception.ConnectClosedError: ConnectClosedError(a.b.c.d.)**


-------------------------------------------------------------------------------------------------------------



In order to avoid such error, and also I want to grep the exact message I have used an alternate solution below::

**op = ss.run('cli -c "request chassis routing-engine master switch"', this=None, timeout=10)
        LOG.info (print (op))
        print (op)
        status = op[1].__contains__('Resolving mastership...')**


The above gives me with no error. 


Anyhowz I am really thankful for your Pyez.

**Comment by rahkumar651991** [comment]
Closing the issue as it seems to be resolved.
